terminusdb/terminusdb

LICENSE

Adding GPL v3

---

library/api.pl
library/capabilities.pl
library/expansions.pl
library/file_utils.pl
library/frame.pl
library/journaling.pl
library/jsonld.pl
library/prefixes.pl
library/speculative_parse.pl
library/validate_instance.pl
library/woql_compile.pl
library/woql_term.pl

Several simple predicate definition optimizations found during an initial quick code review.

Predicate definition optimizations

---

library/casting.pl
library/database.pl
library/file_utils.pl
library/frame.pl
library/json_woql.pl
library/jsonld.pl
library/prefixes.pl
library/triplestore.pl
library/types.pl
library/utils.pl
library/woql_compile.pl
test/test_utils.pl

The performance boost should be noticeable.

Load library(apply_macros) to optimize metacalls and lambda expressions

---

library/xsd_parser.pl

Logtalk linter strikes again 😛

Replace call to deprecated sign/2 predicate with call to sign/1 function

---

library/woql_compile.pl

Fix woql_compile module missing use_module directive

---

index.tpl

base tag in index.tmp is causing a bad bug in the console

base tag in index causes console bug

---

terminus-schema/vio.owl.ttl

typo of violation within vio:ClassInheritanceViolation

typo - violtion

---

library/terminus_bootstrap.pl

Another Logtalk linter complaint 😛

Delete duplicated predicate export in terminus_bootstrap

---

library/db_init.pl
library/db_repo.pl
library/db_util.pl

Also fixes a syntax typo error in `db_util.pl`.

Fix missing import of module syntax

---

library/resolve_query_resource.pl

There is no `pcre:re_matchsub/3` predicate.

Fix missing argument in pcre:re_matchsub/4 predicate calls

---

docs/TUTORIALS.md

Fix tutorial repo URL MD formatting.

Fix TUTORIALS.md

---

src/core/api/api_error.pl
src/terminus-schema/api.owl.ttl

Fixing bad return message for database does not exist in prefix lookup

Adding error handling for database_does_not_exist.

---

.github/workflows/docker-publish.yml
Dockerfile
src/core/api/api_optimize.pl

Upping store version and adding imprecise rollup

Upping terminus store prolog version

---

src/core/triple/literals.pl
src/core/triple/triplestore.pl

Found source of erroneous repeated solutions.

Fix duplicate results from queries.

---

.github/workflows/docker-publish.yml
Dockerfile
src/core/api/api_error.pl
src/core/api/api_optimize.pl
src/terminus-schema/api.owl.ttl

Fix the optimization race condition by using the version on the label to be updated in a test-and-set

Remove optimize labelled graph race condition

---

src/core/account/capabilities.pl

The permission checking was too strict. If any other use makes a
DB, the admin does not have write access. Now it checks whether
you are actually admin.

Fix admin not having access to other databases

---

docs/reference/API.md
docs/reference/WOQL_JSON.md
docs/reference/XSD_WHITELIST.md

Adding information about xsd types and xdd types

Improvements to documentation

---

src/core/triple/literals.pl

This fixes the issue of anyURI not being readable

Updating storage_literal/2 to ignore casting on anyURI

---

docs/CONTRIBUTING.md

The "dev branch does not exist, so I updated the .md and proposed for the pull requests to be directed to the "main" branch.

Renamed "dev" to "main"

---

docs/CONTRIBUTING.md

Edited the following: 
Please send a [GitHub Pull Request](https://github.com/terminusdb/terminusdb-server/pull/new/main) to the main branch.
Please write clear log messages with your commits. Small changes can be a one line message, 
but big changes should have a descriptive paragraph with a newline after the title in the message.

edit link at Contributing.md

---

.github/workflows/docker-publish.yml
Dockerfile
src/core/api/db_delete.pl
src/core/triple.pl
src/core/triple/triplestore.pl

* Bumps `terminus_store_prolog` version
* Closes #350

Database (named graph) deletion using terminus-store

---

src/core/document/json.pl

You really were there and held my hand while doing it, so is there a point of explaining it?

updated json documentation in class_frame.

---

src/core/api/api_bundle.pl
src/core/api/api_remote.pl
src/core/transaction/repo_entity.pl

the Bundle bug was fixed, it was occurring because the head of the repo was not deleted properly and this was leading to schema failure. 
Added some tests too.

bug fixed, tests added

---

src/core/document/json.pl

Subdocument update

---

src/core/api/api_document.pl

replace document with multiple documents (PUT method) with the same id  now returns an error. All tests passing.

bug in PUT resolved.

---

src/core/document/json.pl

Add schema context tests

---

docs/reference/WOQL_JSON.md
src/core/api/api_prefixes.pl
src/core/api/db_create.pl
src/core/api/db_push.pl
src/core/document.pl
src/core/document/json.pl
src/core/document/query.pl
src/core/document/schema.pl
src/core/query/ask.pl
src/core/query/woql_compile.pl
src/terminus-schema/woql.json

Adding changes to context documentation so we have a place to hang our schema global information including authorship

Context documentation

---

docs/reference/ref.md
docs/reference/repository.md
docs/reference/system_schema.md
docs/reference/woql.md
src/utils/compile_docs.sh
src/utils/jsonToMDConverter/package.json
src/utils/jsonToMDConverter/script.js

javascript app to generate automatic documentation from schemata

Add script for documentation generation

---

src/core/api.pl
src/core/api/api_document.pl
src/server/routes.pl

Add replace IDs to formerly empty response

---

src/cli/main.pl
src/core/api/api_document.pl

The document api was not yet checking authorization. Now it does.

Document auth

---

Makefile
docs/reference/ref.md
docs/reference/repository.md
docs/reference/system_schema.md
docs/reference/woql.md
src/terminus-schema/ref.json
src/terminus-schema/repository.json
src/terminus-schema/system_schema.json
src/terminus-schema/woql.json
src/utils/jsonToMDConverter/script.js

Add some fixes to js script to process documentation

Schema documentation script

---

src/core/api/db_create.pl
src/core/document/json.pl
src/core/document/schema.pl
src/core/triple/literals.pl
src/core/util/utils.pl

* In schema checker and `create_db`
* Make `uri_has_protocol` a bit more stringent
* Fixes #416

Add base and schema prefix URI checks

---

docs/DOCUMENT.md

Document api doc

---

src/core/transaction/validate.pl

querying an empty branch should no longer error

---

src/core/document/instance.pl
src/core/document/json.pl
src/core/document/schema.pl

changing key strategy now validates existing objects

---

src/core/query/json_woql.pl
src/core/query/woql_compile.pl
src/terminus-schema/woql.json

* Add DeleteTriple tests
* Fixes #492

Fix graph/graph_filter, DeleteTriple, etc.

---

src/core/document/instance.pl
src/core/document/json.pl
src/core/document/schema.pl

proper list and array cardinality checking

---

src/core/query/woql_compile.pl

Less than was dying on resource access control checking

Access control fix

---

src/core/api/api_error.pl
src/core/api/db_create.pl
src/server/routes.pl

Prefix errors

---

src/server/routes.pl

default schema checking to true on new db creation

---

src/core/account/user_management.pl
src/core/api/api_bundle.pl
src/core/api/api_document.pl
src/core/api/api_error.pl
src/core/api/api_prefixes.pl
src/core/api/api_remote.pl
src/core/api/db_create.pl
src/core/api/db_rebase.pl
src/core/document/instance.pl
src/core/document/json.pl
src/core/document/schema.pl
src/core/query/woql_compile.pl
src/core/transaction/descriptor.pl
src/core/transaction/validate.pl
src/core/triple/constants.pl
src/terminus-schema/system_instance_template.json
src/terminus-schema/system_schema.json

Add lexical subdocument addressing

Id generation

---

src/core/query/woql_compile.pl

Fix `using` in resource

---

src/core/document/json.pl
src/core/document/schema.pl

Adding fix to #383

---

src/core/document/json.pl

Fixes the null elaboration

---

src/server/routes.pl

Catch json(unexpected_end_of_file) and throw malformed_json_payload

---

src/server/routes.pl

Reverts terminusdb/terminusdb#522

Revert "Catch json(unexpected_end_of_file) and throw malformed_json_payload"

---

src/core/api/api_document.pl
src/core/api/api_error.pl
src/core/document/json.pl

improved submitted DocId error

---

src/server/routes.pl

Cryptic rebase error fixed.

---

src/core/api/api_document.pl
src/core/api/api_error.pl
src/core/util.pl
src/core/util/utils.pl

report the duplicate ids when trying to insert duplicate documents

---

src/core/api/api_error.pl

proper error for schema replacement with missing context

---

src/core/api/db_rebase.pl

Throw errors for rebase branches not found

---

src/core/document/json.pl
src/core/query/woql_compile.pl

change all hashing strategies to SHA256

---

docs/RELEASE.md
docs/release.md

This is both a description and a proposal for how to handle our release process.
Leaving this as a draft request so people can have a look.

Document explaining our release process

---

src/core/api/api_document.pl
src/core/api/api_error.pl
src/core/document/json.pl

Errors for no key or key type, unknown key type

---

src/core/document/json.pl
src/core/triple/casting.pl

could be causing difficulties with time stamps
fixes #594

Floats not marshalled correctly

---

src/core/query/woql_compile.pl

Mark tests with external links as fixme

---

src/core/util/json_log.pl

This is a last handful of changes to make logging slightly better.

Log improvements

---

src/config/terminus_config.pl

update version to reflect the upcoming release

---

src/core/document/json.pl
src/core/query.pl
src/core/query/global_prefixes.pl

Normalize values

---

src/core/util.pl
src/core/util/json_log.pl
src/server/routes.pl

This pull request will resolve a bunch of logging issues:

Further log improvements

---

.github/workflows/ci.yml
Dockerfile

New version of store which fixes the rollup bug and upgrades dependencies.

Upgrade to terminus_store_prolog 0.19.2

---

docs/RELEASE_NOTES.md
src/config/terminus_config.pl
src/server/routes.pl

Preparing 10.0.5

---

src/core/account/user_management.pl
src/core/api.pl
src/core/api/api_user_organizations.pl
src/server/routes.pl
src/terminus-schema/system_schema.json

Adding an endpoint for recovery of organizations and associated databases.

Add endpoint for front end.

---

src/core/api/api_error.pl
src/core/document/query.pl

Query error coverage

---

src/server/routes.pl
tests/test/common-http-errors.js

And fix missing `()` on `util.randomString()` in tests.

Check content-type in /api/document

---

src/core/api.pl
src/core/api/api_document.pl
src/core/api/db_rebase.pl
src/core/document.pl
src/core/document/json.pl
src/server/routes.pl
tests/lib/document.js
tests/test/document-auth.js

Replace document now takes a flag "create" which if set to "true" will create a new document resource if it does not exist already.

Adding update or insert functionality

---

src/core/query.pl
src/core/query/json_woql.pl
src/core/query/jsonld.pl
src/core/query/path.pl
src/core/query/query_response.pl
src/core/query/woql_compile.pl
src/core/util.pl
src/core/util/utils.pl
src/terminus-schema/woql.json

Adding templating and other features needed to make an effective document path query as per discussion #729

Document path

---

src/core/api/api_document.pl
src/core/api/api_error.pl
src/core/document/json.pl
src/core/query.pl
src/core/query/jsonld.pl
tests/lib/document.js
tests/test/document-auth.js

* Reject non-string `@id` and `@type` values.
* Generate string `@id` for `null`, `false`, and `true`.
* Test for the above

Handle various schema @id and @type

---

.github/workflows/ci.yml
Dockerfile

Raise store version to 0.19.4 to get the `sp_card/4` predicate.

raise store version to 0.19.4

---

src/core/query/json_woql.pl
src/core/query/path.pl
src/core/query/woql_compile.pl
src/terminus-schema/woql.json

Adding "any" path pattern ( '.' in regex )

---

src/core/api/api_document.pl
src/core/api/api_error.pl
src/core/util.pl
src/core/util/param.pl
src/core/util/utils.pl
src/server/routes.pl
tests/lib/document.js
tests/lib/params.js
tests/lib/util.js
tests/package-lock.json
tests/package.json
tests/test/document-auth.js
tests/test/document-delete.js
tests/test/document-get.js

* Create `src/core/util/param.pl` for checking JSON and search parameters
* Fix many issues with unchecked bad parameter types
* Add tests for document query and deletion
* Consolidate error reports under `bad_parameter_type`
* Remove unused or replaced error responses

Improve input checking for document GET/DELETE

---

src/core/api/api_error.pl
src/core/api/api_frame.pl
src/core/document.pl
src/core/document/json.pl
src/server/routes.pl

add generation for all frames

---

src/core/api/api_error.pl
src/core/document/json.pl
tests/lib/document.js
tests/test/document-auth.js

* Check for a missing `@type` in submitted schema
* Consolidate errors for missing `@id` and `@type` into one error type
* Improve tests for missing fields

Improve missing field checks

---

tests/test/document-auth.js

Add test for subdocument schema with `@documentation`

---

src/core/api/api_document.pl
src/core/document/json.pl
src/server/routes.pl
tests/lib/document.js
tests/test/document-get.js

Also rename variable Compress to Compress_Ids for consistency
Fixes #802

Create alias parameter prefixed called compress_ids

---

.github/remove-old-docker-images.py
.github/workflows/ci.yml
.github/workflows/remove-old-docker.yml

Each commit to `main` will get a dev tag that looks like:
dev-COMMITHASH
This makes it easier to test specific dev builds before release.
After a week, they will be cleaned up again.

ci: add new dev image for each commit and clean them up

---

docs/release-steps.md

This is our initial documentation on the steps we go through in a release.

Add a release steps document

---

src/core/api/api_document.pl
src/core/util.pl
src/core/util/utils.pl

Fix id capture when documents are submitted as a list

---

src/core/api/api_document.pl
src/core/api/api_error.pl
src/core/document/json.pl
src/core/query/woql_compile.pl

Return an error when insert or replace document is given a subdocument

---

docs/RELEASE_NOTES.md

Release notes of 10.0.15

---

SECURITY.md

* `< 9.0` makes me wonder what happened to `>= 9 && < 10`. I simplified it.
* I reordered things to make it more clear to myself.

Make a few improvements to @rooij's SECURITY.md

---

src/core/query/ask.pl

Prevent stupid bugs from happening.

Check the arguments to create_context

---

tests/package-lock.json

Fixes https://github.com/advisories/GHSA-qrpm-p2h7-hrv2

Upgrade tests package dependencies

---

src/core/query/woql_compile.pl

Fix insert_document_forget_uri

---

src/core/document/diff.pl
src/core/document/patch.pl

Deep value patch and diff

---

src/core/document/patch.pl

It polluted the test outputs.
Fixes #931

Remove debug writeq in patch test

---

src/config/terminus_config.pl
src/core/api/api_init.pl
src/core/util/test_utils.pl
src/server/routes.pl

We shouldn't load it from filesystem but load it inside the binary.

Read files as a dynamic predicate instead of loading it from fs

---

src/core/document/instance.pl
src/core/document/json.pl
src/core/document/schema.pl

It would be nice to have Nth Order lists, and actually this isn't very hard.

Table type implementation

---

src/core/api/api_document.pl
src/core/util.pl
src/core/util/utils.pl

Properly reset the captures when a transaction is rerun

---

src/core/api/api_error.pl
src/core/document/json.pl
src/core/query/json_woql.pl
src/core/transaction/ref_entity.pl
src/server/routes.pl
tests/lib/woql.js
tests/test/woql-auth.js
tests/test/woql-noauth.js

* Fix #900: InsertDocument without commit_info
* Fix #917: DeleteDocument
* Fix #918: UpdateDocument
* Add other /api/woql tests

Fix and test WOQL/Document queries

---

src/core/document/patch.pl

In our big refactor dance I accidentally still referred to old predicate names. Also, one of the existing tests is no longer relevant. this is all fixed now, and the unit tests should run again.

fix predicate calls regarding tables

---

tests/test/db-name-validation.js

I completely missed an integration test file in a previous pull request. Here it is again.

integration tests for org and db name validation

---

src/core/document/patch.pl

This should allow well formed diffs to be used in all versions

Table patch logic (not diff)

---

.gitignore
Dockerfile
Makefile
src/bootstrap.pl
src/config/terminus_config.pl
src/core/account.pl
src/core/account/capabilities.pl
src/core/api/api_error.pl
src/core/document/diff.pl
src/core/document/instance.pl
src/core/document/json.pl
src/core/document/patch.pl
src/core/document/schema.pl
src/core/util.pl
src/interactive.pl
src/load_paths.pl
src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/terminusdb-community/Cargo.toml
src/rust/terminusdb-community/src/lib.rs
src/rust/terminusdb-dylib/Cargo.toml
src/rust/terminusdb-dylib/src/lib.rs
src/server/main.pl
src/start.pl

This refactor allows building of an enterprise companion repository that lives in a sibling folder of the terminusdb source.
More information (for core contributors) can be found in our internal `terminusdb-enterprise-experimental` repository.
Note that the primary build target remains the community build. This pull request should not actually change how the build is done in CI.

Refactor build to allow building with a companion enterprise repository

---

.github/workflows/ci.yml

We'll add a better version back in later.

Remove lint for now

---

.github/workflows/ci.yml

Fix the enterprise trigger. This time tested a lot on a WIP branch.

ci: trigger enterprise build on push to main

---

src/core/document/diff.pl

Fix patch cost, fix aggregation, lower move costs

Fix deep patch cost evaluation

---

src/core/api/api_patch.pl
src/core/document/diff.pl
src/server/routes.pl

Fixing JSON dict tags

---

src/server/routes.pl

routes: remove message_handler

---

.github/workflows/ci.yml

Before (example):
```
ERROR: ./generate_predicates_json.pl:2| Predicate main(_43404) not found
ERROR: ./generate_predicates_json.pl:7| Predicate member(_43404,_43406) not found
ERROR: ./generate_predicates_json.pl:14| Predicate xref_public_list(_43404,_43406,_43408) not found
ERROR: ./generate_predicates_json.pl:14| Predicate append(_43404,_43406) not found
```
After (example):
```
ERROR: ./generate_predicates_json.pl:2| Predicate "main/1" not found
ERROR: ./generate_predicates_json.pl:7| Predicate "member/2" not found
ERROR: ./generate_predicates_json.pl:14| Predicate "xref_public_list/3" not found
ERROR: ./generate_predicates_json.pl:14| Predicate "append/2" not found
```

increase linter version that improves formatting

---

src/core/document/instance.pl
tests/test/document-auth.js

Optional Cardinality failure on tagged union

---

.github/workflows/ci.yml

Saves time for building the Docker

ci: try layer caching

---

.github/workflows/ci.yml
Dockerfile
src/core/api/api_info.pl
src/core/api/api_init.pl
tests/test/info_ok.js

Add terminusdb.git_hash to /api/info

---

src/core/api/api_document.pl
src/core/api/api_error.pl
src/core/document/instance.pl
src/core/document/json.pl
src/core/document/schema.pl

Unit type fixes

---

.github/workflows/ci.yml
tests/lib/agent.js
tests/lib/organization.js
tests/test/auth.js
tests/test/organization.js

This is part of the work for #941 and needed for adding CLI tests.

Default user and password for tests

---

Makefile
src/core/document/json.pl
src/core/query/jsonld.pl

Unit test fixes for regressions after failure to run tests.

---

src/core/api/api_document.pl
src/core/document/instance.pl
src/core/document/json.pl
src/core/document/schema.pl
tests/test/document-auth.js

Add cardinality checking to sets, allowing min, max, or min and max cardinality.

Cardinality

---

.github/workflows/ci.yml

See <https://yaml-multiline.info/> for the craziness that is YAML
multiline strings.

Remove newline from push_docker_required

---

.github/workflows/check.yml
.lint_config.pl
src/bootstrap.pl
src/core/api/db_branch.pl
src/core/api/db_fast_forward.pl
src/core/api/db_push.pl
src/core/api/db_rebase.pl
src/core/document/json.pl
src/core/query/woql_compile.pl
src/core/transaction/descriptor.pl
src/interactive.pl
src/library/plunit.pl
src/load_paths.pl
src/start.pl

Adding plunit custom version which does correct concurrency counts

---

tests/bench/document-instance-insert-first.template.js
tests/bench/document-schema-insert-first.template.js

For debugging when these operations fail during CI. See #1062.

Print benchmark document insert response

---

src/core/query.pl
src/core/query/jsonld.pl
src/core/query/woql_compile.pl

Update test and add type marshalling to appropriate namespace

Adding dictionary template infra.

---

src/core/account.pl
src/core/account/capabilities.pl
src/core/api.pl
src/core/api/api_document.pl
src/core/api/api_patch.pl
src/core/document/diff.pl
src/core/util.pl
src/core/util/data_version.pl
src/server/routes.pl
tests/lib/endpoint.js
tests/package-lock.json
tests/package.json
tests/test/diff-id.js

Adding JSON version diff between specific commits

---

docker-compose.yml

PUBLIC_URL is not used anymore.

Remove deprecated docker ENV variables

---

Makefile
docs/BUILD.md

* Add `make install-deps` for installing pack dependencies
* Add `clang` to dependency installation instructions
* Fixes #852

Update build instructions

---

src/config/terminus_config.pl
src/server/routes.pl

Try to determine upload path from env var.

---

tests/.eslintrc.js
tests/lib/document.js
tests/lib/endpoint.js
tests/package-lock.json
tests/package.json
tests/test/data-version.js
tests/test/diff.js
tests/test/document-auth.js
tests/test/document-get-hierarchy.js
tests/test/document-get.js
tests/test/organization.js
tests/test/woql-auth.js

* Update everything, including minimist.
* Apply lint fixes.

Update tests package dependencies

---

src/core/api/api_document.pl
src/core/document.pl
src/core/document/json.pl

Fix replace all context

---

src/cli/main.pl
src/core/api.pl
src/core/api/api_document.pl
src/core/util.pl
src/core/util/json_stream.pl
src/core/util/utils.pl
src/server/routes.pl

Cli replace

---

src/cli/main.pl

Halt on closed user output

---

.github/workflows/ci.yml

Instead of always cloning main, the payload SHA should be passed.

Payload enterprise sha

---

src/core/api/api_error.pl
src/core/query.pl
src/core/query/resolve_query_resource.pl
src/core/query/woql_compile.pl

Fix `using` so resolution works on absolute descriptors

---

src/core/document/diff.pl

Adding fix and test for copy value in deep list

---

Dockerfile

Fixes a variable in a test that should have been a singleton.

Update tus to v0.0.10

---

.github/workflows/ci.yml

Add a CI job to trigger an action on `terminusdb-docs` that commits any
changes to the docs from `terminusdb`.

Add trigger_docs_update

---

src/core/document.pl
src/core/document/instance.pl
src/core/document/json.pl
src/core/document/json_rdf.pl
tests/test/document-auth.js

Fixes #1222 and id dropping from JSON

---

src/core/document/inference.pl
src/core/document/json.pl

Backwards reading of subsumption caused failure on range type.

---

.github/workflows/check.yml
Dockerfile
src/library/terminus_store.pl

The Dockerfile now runs as a non-root user by default. This fixes https://github.com/terminusdb/terminusdb/issues/1218

Dockerfile security enhancements

---

src/cli/main.pl

Send query output to stdout

---

src/core/document/instance.pl
src/core/document/json.pl

Fix for #1272

---

docs/terminusdb.1.ronn
docs/terminusdb.1.ronn.template
src/cli/main.pl

Explain DB spec in man page

---

README.md

Changing readme slightly.

---

src/core/document/json.pl
src/core/document/schema.pl

Adding unfoldable option to schema

---

src/core/document/json.pl
src/core/document/schema.pl

Cycle checking

---

src/cli/main.pl
src/core/api.pl
src/core/api/api_access_control.pl
src/server/routes.pl
tests/test/capabilities.js

Access control refinement

---

docs/terminusdb.1.ronn
src/cli/main.pl
src/core/api/api_error.pl
src/server/routes.pl

Cli bug fixes

---

src/cli/main.pl
src/core/api.pl
src/core/api/api_access_control.pl
src/core/api/api_error.pl
src/server/routes.pl

Restrict user capabilities to *only* those within the organization

---

src/core/api/api_error.pl

Allow lists of incorrect results in actions error for roles

---

src/core/account/capabilities.pl
src/core/api/api_access_control.pl
src/core/triple.pl
src/core/triple/literals.pl
tests/test/capabilities.js

Organization user auth

---

src/core/document/instance.pl
src/core/document/json.pl

Fix for #1324

---

Dockerfile
Makefile
distribution/Makefile.deps
src/cli/main.pl
src/config/terminus_config.pl
src/load_paths.pl
src/server/routes.pl
tests/test/dashboard.js

Add dashboard routing

---

src/core/api/api_access_control.pl
tests/test/capabilities.js

Fixes passwordless user bug in API

---

src/core/api/api_access_control.pl
tests/test/capabilities.js

Add correct username to error + test

---

src/server/routes.pl
tests/test/db-noauth.js

Forgot verbose parameter in /api/db

---

docs/terminusdb.1.ronn
src/cli/main.pl
src/core/api/api_error.pl
src/core/api/api_reset.pl
src/core/api/db_branch.pl
tests/test/branch-auth.js

Full or relative paths in branch create with default main

---

docs/openapi.yaml
src/core/account/capabilities.pl
src/core/api.pl
src/core/api/api_frame.pl
src/core/util/param.pl
src/server/routes.pl
tests/lib/remote.js
tests/test/frame.js
tests/test/organization.js
tests/test/remote-auth.js

Api fixups

---

src/core/document/inference.pl
src/core/document/json.pl

Fixes a bug where expanded enums are not recognised by type inference.

Oversight in enum inference

---

distribution/init_snap.sh
distribution/snap/snapcraft.yaml

Fix the integration tests and make dashboard able to run inside the snap as well. Also upgraded the snap to use Ubuntu 20.04 instead of 18.04.

Snap fix dashboard

---

docs/RELEASE_NOTES.md

Adding release notes for v10.1.2

---

src/cli/main.pl
tests/test/cli-options.js

Cli error fix

---

src/cli/main.pl
src/core/api/api_db.pl
src/core/api/api_error.pl
src/core/document/json.pl
tests/test/cli-db.js

Fixes #1340 + some strange behaviour on listing of non-existing databases when not seeking metadata

Db lists cli

---

src/core/api/api_error.pl
tests/test/cli-query.js

Catching errors from CLI

---

src/core/document/json.pl
src/core/document/schema.pl

Adding inheritence check

---

src/core/document/json.pl
src/core/util/iana.pl

Fix the possibility of reuse of tag types

---

src/core/api/api_error.pl
src/core/api/db_branch.pl
tests/test/cli-branch.js
tests/test/cli-db.js

branch delete needs better error reporting and not to allow deletion of main

---

src/core/api/api_error.pl

Adding coverage for permissions error

---

src/core/document/json.pl

Not really something which Fixes #733 since it is already fixed.

Check to make sure #733 does not reappear

---

src/core/api/api_error.pl
tests/test/document-auth.js

Fixes #845

---

src/core/api/api_access_control.pl
tests/test/cli-user.js

User password update was dropping capabilities

Fix user password udpate

---

src/rust/terminusdb-store-prolog/Cargo.toml

Disable noreadlock feature

---

README.md

docs(Issues) : link added to Issues badge #1375

---

src/core/api/api_error.pl
src/core/document/json.pl
tests/test/document-auth.js

Fixes #1278

---

src/core/api/api_access_control.pl
src/core/api/api_error.pl
tests/test/cli-db.js

Fixes #1368

---

distribution/Makefile.deps

A newer version of the dashboard has been released.

Use newer version of the dashboard

---

src/core/api/api_document.pl
src/core/api/api_error.pl
src/core/document/json.pl
src/core/document/schema.pl
src/core/util.pl
tests/test/cli-doc.js
tests/test/document-auth.js
tests/test/frame.js

Multilanguage comment label property

---

src/core/document/json.pl
src/core/document/schema.pl

Inherit documentation

---

docs/openapi.yaml

Add log endpoint openapi

---

docs/RELEASE_NOTES.md

Add release notes

---

.github/workflows/ci.yml
distribution/snap/snapcraft.yaml
docs/release-steps.md
src/config/terminus_config.pl

Cog increase version

---

src/terminus-schema/woql.json

AddData in WOQL schema twice

---

src/core/document/json.pl
src/core/document/schema.pl

Multilanguage inherits

---

src/cli/main.pl
src/core/api/api_error.pl
src/core/triple.pl
src/core/triple/literals.pl
src/core/triple/turtle_utils.pl
tests/served/MW00KG01635.trig
tests/test/cli-triples.js
tests/test/triples.js

Allow loading of trig files

---

src/core/api.pl
src/core/api/db_create.pl
src/server/routes.pl
tests/test/db-auth.js

Add test for database uri

---

src/core/api/api_error.pl
src/core/api/db_create.pl
src/core/triple.pl
src/core/triple/triplestore.pl

Validate db name length at the start of db creation process

---

docs/terminusdb.1.ronn
src/cli/main.pl
src/server/routes.pl
tests/test/capabilities.js
tests/test/cli-capabilities.js

Grant by name

---

src/core/document/inference.pl
src/core/document/json.pl
src/core/query/woql_compile.pl

Fix oneof frames

---

src/core/query/woql_compile.pl

Fix typeof triggering on suspend

---

docs/openapi.yaml

Adding scope type to OpenAPI spec

---

src/cli/main.pl
src/core/api/api_error.pl
src/core/api/api_patch.pl
src/server/routes.pl
tests/test/cli-diff.js
tests/test/diff-id.js

Diff error handler

---

src/core/api/api_document.pl
src/core/api/api_patch.pl
src/core/document.pl
src/core/document/json.pl
tests/test/diff-id.js

Json diff for top level `sys:JSONDocument`

---

src/core/api/api_error.pl
src/server/routes.pl
tests/test/diff-id.js

Better error message on diff

---

docs/terminusdb.1.ronn
src/cli/main.pl

Cli squash

---

docs/openapi.yaml

The class frame endpoint was not properly documented and I added metadata about corresponding Python functions for each endpoint.
This makes it easier for us to `grep` through the OpenAPI spec by doing `grep not_implemented` to see which endpoints have not yet been implemented in the Python client. We could also develop proper linting later and add the JS client as well.

Openapi fixes

---

src/core/document/json.pl
src/core/document/schema.pl

Fix documentation inheritance with monolingual docs.

---

src/rust/terminusdb-community/src/value.rs
tests/test/cli-doc.js

Add regression test to lang values

---

tests/test/cli-doc.js

Adding double escape regression test

---

docs/RELEASE_NOTES.md

Update Release Notes

---

.github/workflows/ci.yml
distribution/snap/snapcraft.yaml
docs/release-steps.md
src/config/terminus_config.pl

Increase version in advance for next release

New version cog

---

src/cli/main.pl
src/core/document/json.pl
src/core/document/schema.pl
tests/test/cli-doc.js

Adding fix for #1532

---

.github/workflows/benchmark.yml
.github/workflows/build.yml
.github/workflows/check.yml
.github/workflows/ci.yml
.github/workflows/non-docker.yml
.github/workflows/remove-old-docker.yml
.github/workflows/snap.yml

This prevents the annoying old Node version warning

Update gh checkout actions

---

distribution/Makefile.deps

New version of dashboard with some bug fixes

Increase dashboard version to 0.0.10

---

src/core/document/json.pl
src/core/document/schema.pl

Fix the metadata field

---

src/core/api/api_error.pl
src/core/document/diff.pl
tests/test/diff-id.js

Diff was allowing explicit copying keys to be diffed in some cases

---

docs/RELEASE_NOTES.md

Release notes update

---

.github/workflows/ci.yml
distribution/snap/snapcraft.yaml
docs/release-steps.md
src/config/terminus_config.pl

Increase version

---

src/core/document/json.pl
src/core/document/schema.pl

Avoid framing json metadata, add test

---

src/rust/terminusdb-community/src/graphql/filter.rs
src/rust/terminusdb-community/src/graphql/frame.rs
src/rust/terminusdb-community/src/graphql/mod.rs
src/rust/terminusdb-community/src/graphql/query.rs
src/rust/terminusdb-community/src/graphql/schema.rs

Fixes https://github.com/terminusdb/terminusdb/issues/1562

Collections over base types

---

src/core/document/diff.pl

Preflight test for lcs

---

src/rust/terminusdb-community/src/graphql/query.rs
src/rust/terminusdb-community/src/graphql/schema.rs
tests/test/graphql.js

Adding "ids" paramter, along with tests.

---

README.md

Changed forum link to our subreddit

Forum to Subreddit

---

src/rust/terminusdb-community/src/graphql/frame.rs
src/rust/terminusdb-community/src/graphql/schema.rs
tests/test/graphql.js

Graphql lego schema

---

.github/workflows/check.yml
distribution/Makefile.deps

It could only switch to the latest tag and did not work anymore if you used an older tag.

Makefile: fix wrong pulling of version of jwt lib

---

src/terminus-schema/system_instance_template.json

Adding more to consumer role

---

src/core/document/json.pl
src/core/document/schema.pl
src/rust/terminusdb-community/src/graphql/frame.rs
src/rust/terminusdb-community/src/graphql/mod.rs
src/rust/terminusdb-community/src/graphql/query.rs
tests/test/graphql.js

Adding graphql inheritance test and implementation

---

src/core/api/api_error.pl
src/core/document/json.pl
tests/test/cli-doc.js

Context not full replace

---

docs/RELEASE_NOTES.md

Adding release notes for v10.1.11

---

src/rust/terminusdb-community/src/graphql/schema.rs
tests/test/graphql.js

Fix back-link kinds

---

src/rust/terminusdb-community/src/graphql/mod.rs
src/rust/terminusdb-community/src/graphql/schema.rs

Removing system from top level

---

.github/workflows/ci.yml
distribution/snap/snapcraft.yaml
docs/RELEASE_NOTES.md
docs/release-steps.md
src/config/terminus_config.pl

Adding release notes for v11.0.0-rc1

---

Dockerfile

Docker: upgrade swipl to v9.0.3

---

.github/workflows/ci.yml
distribution/snap/snapcraft.yaml
docs/release-steps.md
src/config/terminus_config.pl

Version bump to rc2

---

src/rust/terminusdb-community/src/graphql/frame.rs

Remove dbg

---

src/rust/terminusdb-community/src/graphql/frame.rs
src/rust/terminusdb-community/src/path/compile.rs
tests/test/graphql.js

Add metadata to frames in GraphQL

---

src/rust/terminusdb-community/src/graphql/frame.rs
src/rust/terminusdb-community/src/graphql/mod.rs
src/rust/terminusdb-community/src/path/compile.rs

Fixes GraphQL crashes due to complex documentation

---

src/core/document/json.pl

Remove unfoldable flag from leaves

---

src/rust/terminusdb-community/src/graphql/mod.rs

Remove extraneous debug prints

---

src/server/routes.pl

Dashboard redirect disabling caused the server to crash when dashboard was accessed, due to an inproper http reply code path. This changes the http reply to trigger SWI-Prolog's default 'gone' page.

Disabled dashboard redirect results in a gone page

---

Dockerfile

Some library incompatibilities caused errors

Dockerfile: use Ubuntu instead of Debian

---

src/core/api/api_error.pl

Give a much better response in the event that there is an error from clone

Clone error

---

.github/workflows/ci.yml
distribution/snap/snapcraft.yaml
docs/RELEASE_NOTES.md
docs/release-steps.md
src/config/terminus_config.pl
src/rust/Cargo.lock
src/rust/terminusdb-community/src/graphql/mod.rs
src/rust/terminusdb-store-prolog/Cargo.toml

V11.0.0 release notes

---

docs/terminusdb.1.ronn
src/cli/main.pl
src/core/api.pl
src/core/api/api_init.pl
src/core/api/api_remote.pl
src/core/api/db_clone.pl
src/core/api/db_fetch.pl
src/core/api/db_push.pl
src/core/document.pl
src/core/document/json.pl
src/core/transaction.pl
src/core/transaction/repo_entity.pl
src/core/util/test_utils.pl
src/server/routes.pl
src/terminus-schema/repository.json
tests/test/cli-clone-push-pull.js
tests/test/local-clone.js

Local clone working

---

src/core/api/api_init.pl

Fix upgrade of database.

---

src/core/account/capabilities.pl

Adding reorder of capabilities, and make anonymous work as fallback

---

distribution/Makefile.deps

Upgrade to TUS version 0.0.13

---

distribution/Makefile.deps

This time we construct our own http calls

Upgrade TUS version to fix SSL error for real

---

Makefile
distribution/Makefile.deps

The softer clean is now called prolog-clean

Makefile: make clean do a real clean

---

src/core/query.pl
src/core/query/constraints.pl

Constraints

---

src/core/query/constraints.pl

Better constraint reporting

---

src/core/query/constraints.pl

Given / when / then constraints

---

src/core/query/constraints.pl

Add customer constraint

---

src/rust/terminusdb-community/src/graphql/query.rs
tests/test/graphql.js

Fix graphql ne queries

---

src/core/api/api_document.pl

Prevent early failure on full schema replace where id is missing

---

src/rust/terminusdb-community/src/value.rs

Support stringy filters on all stringy types, not just strings

---

docs/openapi.yaml
src/core/api.pl
src/core/api/api_document.pl
src/core/api/api_error.pl
src/core/api/api_patch.pl
src/core/document.pl
src/core/document/apply.pl
src/core/document/json.pl
src/server/routes.pl
tests/lib/api/path.js
tests/test/patch.js

This endpoint will apply a patch to a resource

Adding Patch Endpoint for Resources

---

src/config/terminus_config.pl
src/core/query.pl
src/core/query/resolve_query_resource.pl
src/core/transaction/descriptor.pl

We want to be able to pinn organizations in memory and not only databases.
Solves: #1762

Implement pinned organization ENV variable

---

src/rust/terminusdb-community/src/graphql/schema.rs

Fix inversion naming issue.

---

.github/workflows/ci.yml
distribution/snap/snapcraft.yaml
docs/release-steps.md
src/config/terminus_config.pl

This was already needed when we released the latest version

New version

---

.lint_config.pl
docs/openapi.yaml
docs/terminusdb.1.ronn
src/cli/main.pl
src/core/api.pl
src/core/api/api_error.pl
src/core/api/api_history.pl
src/core/api/api_patch.pl
src/core/document/history.pl
src/core/query/json_woql.pl
src/core/query/jsonld.pl
src/core/query/metadata.pl
src/core/query/path.pl
src/core/query/resolve_query_resource.pl
src/core/query/woql_compile.pl
src/core/util/utils.pl
src/server/routes.pl
tests/test/history.js

This provides history to individual documents.

Object history API

---

src/core/api/api_optimize.pl

Fix optimize to take into account schema

---

docs/openapi.yaml

Adding open api history docs

---

src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/terminusdb-store-prolog/Cargo.toml

This introduces the memory optimizations from store.

Depend on last released version of terminus-store

---

src/core/document/history.pl

Fix bug which was reporting subdocuments in changed ids.

---

docs/RELEASE_NOTES.md

We're doing a hotfix release as it turns out that 11.0.4 was breaking diff views when subdocuments were involved.

Release notes for 11.0.5

---

src/rust/terminusdb-community/src/doc.rs
src/rust/terminusdb-community/src/graphql/frame.rs
src/rust/terminusdb-community/src/graphql/schema.rs
src/rust/terminusdb-community/src/value.rs

Graphql json fix

---

src/core/api/api_init.pl

Add system graph update logic

---

src/core/document/migration.pl

Be stricter about weakening of contexts

---

.github/workflows/check.yml
.github/workflows/ci.yml
.github/workflows/snap.yml
distribution/snap/snapcraft.yaml
docs/terminusdb.1.ronn

The required libprotobuf libraries needed to be installed. The tests also needed to connect to `127.0.0.1` instead of localhost.

Fix snap build

---

docs/terminusdb.1.ronn
src/cli/main.pl
src/core/api/api_patch.pl
src/core/document/json.pl
src/core/util.pl
src/core/util/utils.pl
src/server/routes.pl
tests/test/diff-id.js

This PR adds paging to the resource diff interface allowing large diffs to be returned in segments with a start and count

Adding paging to diffs

---

src/core/document/patch.pl

Fix set diff

---

src/core/api/api_error.pl
tests/test/cli-clone-push-pull.js

Fix for push remote error catch

---

src/rust/terminusdb-community/src/graphql/frame.rs
tests/test/graphql.js

Treat oneOf correctly in GraphQL query
Fixes #1818

Graphql query fixes

---

src/server/routes.pl

Fix interaction between compression and sessions

---

src/rust/terminusdb-community/src/graphql/query.rs
src/rust/terminusdb-community/src/graphql/schema.rs
src/rust/terminusdb-community/src/value.rs
tests/test/graphql.js

Fix ordering of graphql stringy numbers

---

src/rust/terminusdb-community/src/graphql/schema.rs
tests/test/graphql.js

Adding type information to decimals

---

src/library/terminus_store.pl
src/rust/terminusdb-store-prolog/src/layer.rs
src/rust/terminusdb-store-prolog/src/lib.rs

Adding op_card

---

docs/openapi.yaml

Updating dry run and verbose parameters

---

docs/README.md

Update README.md - fix docs link

---

src/core/document/migration.pl

Fix metadatda and docs to avoid pollution with extraneous migration

---

src/rust/terminusdb-community/src/graphql/frame.rs
tests/test/graphql.js

Reserved words graphql

---

src/core/api/api_init.pl

Bump the ref version

---

src/core/api/db_fetch.pl

Fix error response

---

src/config/terminus_config.pl
src/core/api.pl
src/core/api/db_fetch.pl
src/core/api/db_pack.pl
src/server/routes.pl

The new way of cloning has problems in different cases that we have to investigate further before we can use it in main.

Revert clone

---

src/core/document/json.pl
src/core/document/migration.pl
src/core/document/schema.pl

Diamond property

---

src/rust/Cargo.lock
src/rust/terminusdb-community/src/graphql/query.rs
src/rust/terminusdb-community/src/graphql/schema.rs
tests/test/graphql.js

Add single level graphql search with test

---

.github/workflows/ci.yml
.gitignore
distribution/Makefile.deps
docker-compose.yml

Add VectorLink and newer dashboard

Add vectorlink

---

README.md

Adding docker compose to readme

---

.github/workflows/check.yml

They should work again after fixing the dependency issue

Re-enable python tests

---

src/rust/terminusdb-community/src/graphql/frame.rs
tests/test/graphql.js

Fix graphql prefix

---

src/rust/terminusdb-community/src/graphql/frame.rs
tests/test/graphql.js

Fix reverse link lookup

---

distribution/Makefile.deps
docker-compose.yml

Increases the versions of the CR API and dashboard for several bug fixes

Increase version number for CR API and dashboard

---

.github/workflows/ci.yml
distribution/snap/snapcraft.yaml
docs/RELEASE_NOTES.md
docs/release-steps.md
src/config/terminus_config.pl

Increase version to v11.1.1-1

---

docker-compose.yml

It would be nice if people don't have to change their docker-compose for this

Make USE_CHANGE_REQUEST changable through .env

---

src/core/query.pl
src/core/query/path.pl
src/core/query/reorder.pl
src/core/query/woql_compile.pl
src/core/triple/literals.pl
src/core/triple/triplestore.pl
src/library/terminus_store.pl

Try to speed up patterns

---

.github/workflows/build.yml

After a build, the resulting image will be checked for fixable security vulnerabilities in the container.

ci: check for fixable container vulnerabilities

---

src/core/document/inference.pl
src/core/document/instance.pl
src/core/document/json.pl

This makes it possible to have foreign lists, sets, options, arrays and cardinalities

Foreign families

---

src/server/routes.pl
tests/lib/document.js
tests/test/document-auth.js

Add merge document to doc interface

---

src/core/document/json.pl
src/rust/terminusdb-community/src/consts.rs
src/rust/terminusdb-community/src/doc.rs

Bare foreign uri

---

src/rust/terminusdb-community/src/graphql/frame.rs
src/rust/terminusdb-community/src/graphql/schema.rs
tests/test/graphql.js

Fix graphql rename

---

src/core/document/instance.pl

Fix foreign objects checking

---

src/core/query/reorder.pl

Fix metasub

---

src/rust/terminusdb-community/src/graphql/frame.rs
src/rust/terminusdb-community/src/graphql/query.rs
src/rust/terminusdb-community/src/graphql/schema.rs
src/rust/terminusdb-community/src/path/compile.rs
tests/test/graphql.js

Fix renaming bug with fully qualifieds

---

src/core/document/json.pl

Return correct min_max cardinality

---

src/rust/terminusdb-community/src/graphql/frame.rs
src/rust/terminusdb-community/src/graphql/schema.rs
tests/test/graphql.js

Fix renaming in subsumption

---

docs/RELEASE_NOTES.md

Release version 11.1.6

---

.github/workflows/ci.yml
distribution/snap/snapcraft.yaml
docs/release-steps.md
src/config/terminus_config.pl

Bump version number

---

src/rust/terminusdb-community/src/graphql/filter.rs
src/rust/terminusdb-community/src/graphql/frame.rs
src/rust/terminusdb-community/src/graphql/mod.rs
src/rust/terminusdb-community/src/graphql/naming.rs
src/rust/terminusdb-community/src/graphql/query.rs
src/rust/terminusdb-community/src/graphql/sanitize.rs
src/rust/terminusdb-community/src/graphql/schema.rs
src/rust/terminusdb-community/src/path/compile.rs

Internal type tracking to avoid misnaming issues.

Graphql typed name tracking cow

---

src/core/query/ask.pl

Add optimization flag to ask

---

docs/RELEASE_NOTES.md

Adding release notes

---

src/core/query/definition.pl

Fix mode declaration for using/from/into

Adding correct mode for using/from/into

---

src/core/api/api_init.pl
src/core/query/definition.pl
src/terminus-schema/woql.json

Adding WOQL mode and type info for clients

---

README.md

Bootstrap is deprecated and should not be used anymore.

Get rid of the references to bootstrap

---

src/core/query/json_woql.pl

Try to relax the AST translator

---

docs/terminusdb.1.ronn
src/cli/main.pl
src/core/api.pl
src/core/api/api_document.pl
src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/terminusdb-store-prolog/Cargo.toml
src/server/routes.pl

This PR introduces document deletion by type.
It also upgrades to the latest version of store.

Delete documents by type

---

src/core/document/migration.pl

Fixes issue #2043 as well as a related issue to do with documentation

Make weakening inferrence more robust

---

src/rust/terminusdb-community/src/graphql/frame.rs
src/rust/terminusdb-community/src/graphql/query.rs
tests/test/graphql.js

Ordering typo in code leads to lt rather than le

---

src/core/query/definition.pl
src/core/query/reorder.pl

Missing cost predicate for one case of path

---

src/core/document/migration.pl
src/core/query.pl
src/core/query/definition.pl
src/core/query/json_woql.pl
src/core/query/query_response.pl
src/core/query/woql_compile.pl
src/terminus-schema/woql.json

Adding optimization to default args, fixing optimize 'is'

---

.github/workflows/ci.yml
distribution/snap/snapcraft.yaml
docs/release-steps.md
src/config/terminus_config.pl

Bump version

---

docs/RELEASE_NOTES.md

Adding release notes for v11.1.11

---

src/core/api/api_init.pl

Upgrade bug

---

src/rust/terminusdb-community/src/graphql/query.rs

Adding allow dead code

---

docs/terminusdb.1.ronn
src/cli/main.pl
src/core/api.pl
src/core/api/api_init.pl
src/core/api/api_woql.pl
src/core/document/json.pl
src/core/query/definition.pl
src/core/query/json_woql.pl
src/core/query/woql_compile.pl
src/core/transaction/database.pl
src/core/util/test_utils.pl
src/server/routes.pl
src/terminus-schema/woql.json
src/test/worldOnt.json

Mutually recursive queries

---

src/core/api/api_error.pl
src/core/api/api_remote.pl
src/core/query/resolve_query_resource.pl

Make graph resources more flexible

---

src/server/routes.pl
tests/lib/woql.js

Add optimization opt-in rather than opt-out

---

README.md

Removed TerminusCMS from README.md

---

src/rust/terminusdb-community/src/graphql/query.rs

Restore natural datetime sorting order.

Fix #2065: reverse datetime order

---

README.md

https://github.com/orgs/terminusdb/discussions/2118

docs: tone of voice based on the discussions #2118

---

docs/RELEASE_NOTES.md

Adds 11.1.14 a section related to the build fixes.

11.1.14 Step 1 and 2: Update RELEASE_NOTES.md

---

.github/workflows/non-docker.yml
Dockerfile
src/core/document/migration.pl

This PR is tentative and needs to be reviewed. Let me know if there are any problems and I'll iterate until I get it right.

Requested fixes for #2153

---

.github/workflows/ci.yml
distribution/snap/snapcraft.yaml
docs/release-steps.md
src/config/terminus_config.pl

This completes the release for v11.1.14 once all has been built, approved and merged.

Steps 3,4,5,6: Updated version to v11.1.14 and next to v11.1.15

---

.github/workflows/check.yml
Dockerfile
src/server/routes.pl
tests/test/cli-schema-migration.js

This PR enables us to upgrade to swipl 9.2.9:
* Updates in swipl [9.0.3 --> 9.2.9](https://www.swi-prolog.org/ChangeLog?branch=stable&from=9.0.3&to=9.2.9)
* Performance update on some platforms with arithmetic
* Additional bug fixes and enhancements
* Keeping it separate from other code
Suggestion is to get issue #2161 fixed and the integration tests running again in the next release and not commit this PR until the integration tests are running again too with 9.2.9.

Issue/upgrade to swipl 9.2.9

---

.github/workflows/code-lint.yml
.github/workflows/native-build.yml
README.md

* Update badges on README
* Improve build actions — skip for changes like this.

Add badges, Improve build actions

---

.github/workflows/native-build.yml
README.md

This PR fixes source code comparison against the main branch on push events.

Fix native build push change check

---

Dockerfile

Fixes the Dockerfile for 11.1.16

Fix dockerfile workdir and packs
