library/triplestore.pl
library/validate_instance.pl
library/woql_compile.pl

Minor cleanup of three calls to deprecated predicates detected by running the Logtalk linter.

Replace calls to deprecated predicates

---

library/database.pl
library/json_woql.pl
library/jsonld.pl
library/literals.pl

Replace calls to deprecated predicate `string_to_atom/2` predicate with calls to  the built-in predicate `atom_string/2`. Found by the Logtalk linter 😛

Replace calls to deprecated predicate string_to_atom/2

---

library/file_utils.pl
library/json_woql.pl

Unused atoms just add to the atom garbage collector burden.

Avoid creating unused atoms by using sub_atom/5 instead of atom_concat/3

---

library/api.pl
library/capabilities.pl
library/casting.pl
library/database_utils.pl
library/expansions.pl
library/frame.pl
library/inference.pl
library/json_woql.pl
library/jsonld.pl
library/prefixes.pl
library/relationships.pl
library/schema.pl
library/schema_util.pl
library/sdk.pl
library/skolemise.pl
library/triplestore.pl
library/turtle_utils.pl
library/validate.pl
library/validate_instance.pl
library/validate_schema.pl
library/woql_compile.pl

This pull request changes `use_module/1-2` directives to use just the name of the module files for local modules instead of using a `library(File)` argument. The main motivation for these changes is to avoid relying on the file search mechanism for the overloaded `library` alias for local modules and thus (1) improve loading times and (2) avoid the unlikely but still possible bug of loading a third-party and thus the wrong module due to an order issue during `library(File)` search. A possible alternative is to define and use an alias other than `library`. E.g. `terminus_core`.
I marked this pull request as WIP due to the scope of the changes and also due to the pending merging of the automatic test workflow as I'm currently unable to test the changes locally on my macOS laptop.

WIP: Fix use module directives

---

library/api.pl

As `cors_catch/2` is declared as a meta-predicate, the meta-argument is implicitly qualified by the runtime. Moreover, the predicate clause doesn't make use of the module qualifier.

Remove redundant module explicit qualification from cors_catch/2 definition

---

library/database.pl

This pull request changes `use_module/1` directives in the `database` module to use just the name of the module files for local modules instead of using a `library(File)` argument. The main motivation for these changes is to avoid relying on the file search mechanism for the overloaded library alias for local modules and thus (1) improve loading times and (2) avoid the unlikely but still possible bug of loading a third-party and thus the wrong module due to an order issue during `library(File)` search.

Fix database module use_module/1 directives for local modules

---

library/capabilities.pl
library/database.pl

These two modules don't import the modules defining those operators

Add missing operator directives to the capabilities and database modules

---

library/prefixes.pl
library/schema.pl
library/sdk.pl
library/triplestore.pl

The `reexport/1` directive subsumes the `use_module/1` directive. The latter is not necessary when the former is used. Same for the arity two variants.

Delete use_module/1 directives subsumed by reexport/1 directives

---

library/sdk.pl

The`sdk` module calls the `get_collection_prefix_list/2` predicate exported by the `prefixes` module.

Add missing import of module prefixes to module sdk

---

library/jsonld.pl

The `jsonld` module calls the `get_global_jsonld_context/1` predicate exported by the `prefixes` module.

Add missing import to module jsonld

---

library/utils.pl

Tested by comparing results with original version.
Note that this pull request doesn't change calls to this predicate. There are a few of them using `once/1` wrappers that should no longer be required.

Make intersperse/2 predicate deterministic

---

library/validate_schema.pl

The `validate_schema` module calls the `database_utils:database_schema/2` predicate but the corresponding `use_module(database_utils)` directive is missing.

Missing import in validate_schema module

---

src/core/transaction/system_entity.pl

I created 388 DBs and it took 90 seconds to list them. But when I fix this query, it takes around 6 seconds. The reason is that the
original query is very slow because it does not take account that Db_Uri could be ground already.
To reproduce the bad performance, create: 388 DBs or something similar:
```python
#!/usr/bin/env python3
from terminusdb_client import WOQLClient, WOQLQuery
amount = 388
client = WOQLClient('https://127.0.0.1:6363')
client.connect(user='admin', account='admin', key='root')
for x in range(0, amount):
db_name = f'db{str(x)}'
client.create_database(db_name, accountid="admin")
```
Then run `./terminusdb list`. As you can see it is very slow.
Apply my commit and it runs way faster.

Fix very slow query when using ./terminusdb list with many dbs

---

src/cli/main.pl
src/core/triple.pl
src/core/triple/triplestore.pl
src/server/main.pl

This patch implements feature request #266. A new flag, -m or --memory with the `terminus serve` command, will start the server with a freshly initialized store that is fully in-memory. optionally, this flag takes an argument which will be used as the password for the admin account. If absent, the admin account will be initialized with password 'root'.
Examples:
```
./terminusdb serve -i -m
./terminusdb serve -i -m my_secret_password
./terminusdb serve -i --memory=my_secret_password
```

implement support for starting TerminusDB in in-memory mode

---

src/cli/main.pl
src/core/api.pl
src/core/api/api_db.pl
src/core/transaction.pl
src/core/transaction/system_entity.pl

Increased performance further. If the account requesting the list
is the super_user/admin, there is no need to get the user object
and query the organization of *every* database.
However, even when a specific user wants a list of their DBs
it is also faster now. Since the name of the database is already
in the user object itself, it does not need to be queried.
This saves addiontal time and also removes the need for the
ground check of the DB URI.
Time went from:
./terminusdb list  6.30s user 1.87s system 103% cpu 7.912 total
To:
./terminusdb list  2.37s user 1.21s system 107% cpu 3.316 total
I also added an extra unit test for existing databases.

Refactor and optimize list db

---

src/core/triple/database_utils.pl

The organization filter was too strict. If the organization
name contained one of the excluded names, it would already
forbid this organization to exist. Even an organization name
called "soundboard" would be forbidden by the existing filter.
Now it only checks whether the whole name is the forbidden word.
The exception to this rule is the | (pipe) character which
should always be forbidden.

Fix organization filter

---

docs/EXPLANATION.md
docs/How_To/Intro.md
docs/REFERENCE.md
docs/TUTORIALS.md

The documentation system now has a new home of its own at https://diataxis.fr/.

Updated link to Diátaxis authoring framework

---

src/core/api/api_error.pl
src/core/api/api_woql.pl
src/terminus-schema/api.owl.ttl

Currently woql syntax errors are not reporting with program navigable errors. This patch fixes the problem.

Adding better woql syntax error checking

---

distribution/init_docker.sh

I lifted [docker-library's `file_env` shell function](https://github.com/docker-library/mongo/blob/b3edd5aacba7e89144cec6020ab34c13116ab44c/4.4/docker-entrypoint.sh#L34) to facilitate the common convention of allowing a `*_FILE` env var, i.e. `TERMINUSDB_ADMIN_PASS_FILE` in this case.
This makes it easier in my case to safely use version control for deployment configuration.
Use bash rather than dash, to avoid "bad completion" error (change the top line to `#!/usr/bin/env bash`).
This supersedes #325, with PR against `dev` as per @rrooij's recommendation.

allow TERMINUSDB_ADMIN_PASS_FILE

---

Dockerfile
src/config/terminus_config.pl
src/core/util/test_utils.pl
src/server/main.pl

The JWKS endpoints consists of sets of keys. This makes it easier
to rotate keys without losing functionality. I updated the
jwt_io lib accordingly, see the tagged 0.0.4 release.
See:
https://github.com/terminusdb-labs/jwt_io/compare/v0.0.3-fix-make...v0.0.4
For a comparison

jwt: support jwks endpoint instead of pub/private key files

---

docs/Intro_Tutorials/Start_With_CLI.md

(It's hard to)[remember] [where the brackets go in markdown links](https://www.markdownguide.org/basic-syntax#links)

docs: fix incorrect markdown links

---

src/core/document/json.pl

This will ensure that subdocuments have a viable key type so we don't end up with complex and difficult to find errors which might result from manually defined keys.

Adding key type restriction for subdocuments

---

docs/reference/ref.md
docs/reference/repository.md
docs/reference/system_schema.md
docs/reference/woql.md
src/utils/jsonToMDConverter/script.js

Remove the unnecessary spaces before and after newlines. `git` doesn't like spaces before newlines.

Remove excess space in document generation

---

.github/workflows/test.yml
Makefile

Currently, `make` doesn't fail if there is an error or warning while building the target with `swipl`. This adds a few `grep`s to do that.

Makefile: fail on error or warning

---

src/core/api/api_document.pl
src/core/api/api_error.pl
src/core/document/instance.pl
src/core/document/json.pl

Most/all insert errors should now give a nice looking error message, and not a stack trace or an incomprehensible json object.

More document error handling

---

src/server/routes.pl

'sub' can't be changed as easy as a custom entry in the token.

jwt: use agent name as username

---

src/cli/main.pl

Ensure that we have proper default prefixes when creating db from cli

---

src/core/account/capabilities.pl
src/core/api/api_prefixes.pl
src/core/api/api_remote.pl
src/core/api/api_squash.pl
src/core/api/db_branch.pl
src/core/api/db_pull.pl
src/core/api/db_unpack.pl

Some problems with 'system:' prefix still being used in auth.

Prefixes auth fix

---

src/config/terminus_config.pl

Transaction retry count, when not supplied through an environment variable at startup, is now computed by doubling the worker count. With the default settings, this will now result in a retry count of 16.
Furthermore, since this configuration setting is retrieved every time a transaction is started, I figured that re-parsing the environment variables and/or recomputing this retry count is a bit silly, so the config predicate is now also tabled, ensuring this happens only once.
Fixes #486.

raise default max transaction retries to multiple of worker count

---

src/core/api/api_error.pl
src/core/util.pl
src/core/util/utils.pl
src/server/routes.pl

Numerical parameters to the document interface were not properly parsed for get requests with a posted query document. A string was expected, which would fail on the numerical representation in a json document.
Furthermore, the existing code did not properly check that the resulting number was an integer. This is now also checked.
Fixes #532.

properly parse count/skip both for input documents and query params

---

src/core/document/json.pl

This fixes the unit test that was failing due to id changes.
However, there's something weird going on here. The id references in the document do not match the actual ids, as one has the + escaped and the other does not. This is probably unintended behavior so I'm not yet merging.
@GavinMendelGleason please have a look.

fix foreign type test that was failing due to new id scheme

---

src/core/document/json.pl

Elaboration context now uses fully expanded properties, something which the rest of the code already seemed to anticipate but wasn't actually happening.
Fixes #545.

document elaboration now works with expanded properties

---

src/server/routes.pl

This change makes minimized json output the default on document retrieval. For pretty printing, users now have to explicitely specify `minimized=false`.
Resolves #550.

return documents in minimized format by default

---

src/core/api/api_error.pl
src/core/document/json.pl

These error conditions are now properly checked and return a good error to the user:
- PUT instance/schema documents for which no version currently exists in the db
- DELETE schema documents that do not exist
Fixes #552.

better error handling for put and delete

---

src/core/api/api_error.pl
src/core/document/json.pl
src/terminus-schema/woql.json

This will at *minimum* alert the user that the schema document being added is not viable rather than silently dropping the insert.

Last chance hotel for schema elaboration

---

src/core/document/json.pl

binding the id when replacing the schema document (Id='@context') fixes the error.
When typing: 
```
curl -X PUT -H "Content-Type: application/json" -u "admin:root" "http://localhost:6363/api/document/admin/test563?graph_type=schema&author=me&message=me" --data-binary '{ "@base": "http://example.com/elements/", "@documentation": {"@authors": ["Gavin Mendel-Gleason"], "@description": "This collection gives the periodic table of the elements with all isotopes together with their names, symbols and masses", "@title": "Periodic Table of the Elements"}, "@schema": "http://example.com/elements#", "@type": "@context"}'
```
The output is:
```
["@context" ]
```
In order to use POST with this, the flag for full replacement should be set to 'true':
```
curl -X POST -H "Content-Type: …
```

Bug fixed.

---

.github/workflows/ci.yml
distribution/appimage/build_script.sh

The AppImage is being created inside the TerminusDB repo itself.
Therefore it does not make sense to clone it again!

appimage: dont clone our own repo

---

src/core/document/query.pl
src/core/util/test_utils.pl

Ensure that query documents can be used to query optional base class fields

---

src/core/document/json.pl

Optionals, sets, arrays and lists were not working properly with key generation.
This now follows the following algorithm:
- For all 4, if there's just a single value, it is treated exactly as if this was a required field. This ensures that the same id is generated, so that in the future, it may be possible to switch between key strategies without having to convert existing objects that are already in line with the new format, such as when going from optional to set, or from required to optional.
- For all 4, if there is no value, the out-of-band value ~~'+'~~ '+none+' (unencoded) is used
- For the list-like types with more than one value, the values are concatenated with an unencoded '++' between them. In case of sets, the list is first sorted to ensure that documents who order the list …

Properly handle key fields that are type containers

---

src/server/routes.pl

Fixes #469.
I have integration tests:
```js
describe('paths not found', (t) => {
const baseUrl = http.baseUrl
http.batch([
new Get('/api'),
new Get('/api/abc'),
new Get('/api/branch'),
new Get('/api/clone'),
new Get('/api/db'),
new Get('/api/document'),
new Get('/api/fetch'),
new Get('/api/optimize'),
new Get('/api/pack'),
new Get('/api/prefixes'),
new Get('/api/pull'),
new Get('/api/push'),
new Get('/api/rebase'),
new Get('/api/reset'),
new Get('/api/schema'),
new Get('/api/triples'),
new Get('/api/unpack'),
]).forEach((r) => {
t.expect(r.status).as('status').toEqual(404)
t.expect(r).toHaveValidJson()
.and(r.json('api:status')).as('api:status').toEqual('api:not_found')
.and(r.json('api:path')).as('api:path').toEqual(r.request.url.replace(baseUrl, ''))
})
})
```

Fallback route handler for unknown paths

---

src/core/account/capabilities.pl
src/core/api/api_error.pl
src/core/api/api_remote.pl
src/core/api/db_branch.pl
src/core/api/db_delete.pl
src/core/query/resolve_query_resource.pl
src/server/routes.pl

* Change `database_does_not_exist` to `unknown_database`
* Fix `resolve_absolute_descriptor` when given a name and `_meta`
* Use input path instead of modified path for `invalid_absolute_path`
* Use `api:not_found` instead of `api:failure`
* Improve branch errors for db and desc
* Fixes #567
I have integration tests:
```js
describe('bad descriptor', (t) => {
const r = http.get('/api/remote/unknowndesc')
t.expect(r.status).as('status').toEqual(400)
.and(r).toHaveValidJson()
.and(r.json('@type')).as('@type').toEqual('api:RemoteErrorResponse')
.and(r.json('api:status')).as('api:status').toEqual('api:failure')
.and(r.json('api:error.@type')).as('api:error.@type').toEqual('api:BadAbsoluteDescriptor')
.and(r.json('api:error.api:absolute_descriptor')).as('api:error.api:absolute_descriptor').toEqu …
```

Improve errors for unknown database

---

src/bootstrap.pl
src/config/terminus_config.pl
src/core/query/query_response.pl
src/core/query/woql_compile.pl
src/core/transaction/descriptor.pl
src/core/transaction/validate.pl
src/core/util.pl
src/core/util/json_log.pl
src/interactive.pl
src/server/routes.pl
src/start.pl

This pull request will replace the existing log with a new type.
The new logger allows structured logging of json structures by severity, and will make an effort to associate each log entry with an ongoing request.
Through the environment variable `TERMINUSDB_LOG_LEVEL`, the desired log level can be set. this can be one of DEBUG, INFO, NOTICE, WARNING or ERROR. The default is INFO. Anything below the desired log level is omitted from the log.
Through the environment variable `TERMINUSDB_LOG_FORMAT`, the desired log format can be set. By default this is `text`, which will just print the log severity, a timestamp and the log message (provided those fields exist in the structured log record). By setting it to `json`, the full structured log record is printed instead.
This log format should …

Implement a new logging strategy

---

src/config/terminus_config.pl
src/server/main.pl

The welcome banner was using server name to build an example url, even though the server name could be wholly unsuitable for that, and is really just meant for identifying purposes in logs. The example url is now hardcoded to localhost.
Furthermore, date printing was locale-dependent, changing the weekday depending on language, which is weird in an otherwise english sentence. It should be locale-independent now.

modify welcome banner to be locale and servername independent

---

distribution/appimage/build_script.sh

The make.sh script has been deprecated

AppImage: use make instead of wrapper make.sh script

---

.github/workflows/non-docker.yml

* It's a less confusing name, since “nightly” could also mean the nightly release of Rust, for example.
* Run every night instead of every weeknight. It doesn't hurt.

Rename Nightly to Non-Docker

---

src/core/api/api_document.pl
src/core/api/api_error.pl
src/core/document/json.pl

Fixes #587.
Here's the new error:
```json
{
"@type": "api:InsertDocumentErrorResponse",
"api:error": {
"@type": "api:DocumentKeyNotObject",
"api:document": {
"@id": "X",
"@key": false,
"@type": "Class"
},
"api:key_value": false
},
"api:message": "Document @key value is not an object: false",
"api:status": "api:failure"
}
```
I've got an integration test:
```js
const r = http.post(`/api/document/${http.user}/dbname?graph_type=schema&author=a&message=m`, {
json: { '@id': 'X', '@type': 'Class', '@key': false },
})
t.status(r).toEqual(400)
t.hasValidJson(r)
t.json(r, '@type').toEqual('api:InsertDocumentErrorResponse')
t.json(r, 'api:status').toEqual('api:failure')
t.json(r, 'api:error.@type').toEqual('api:DocumentKeyNotObject')
t.json(r, 'api:error.api:key_value').toEqual(false)
t.json(r, …
```

Error if @key value is not dict

---

src/core/api/api_error.pl

Fixes #603
Integration test:
```js
describe('duplicate field (#603)', (t) => {
const r = http.post('/api/db/u/d', {
text: '{"comment":"c","comment":"c","label":"l"}',
headers: { 'Content-Type': 'application/json' },
})
t.status(r).toEqual(400)
t.json(r, '@type').toEqual('api:DuplicateField')
t.json(r, 'api:status').toEqual('api:failure')
})
```

Better error for duplicate field

---

tests/lib/branch.js
tests/lib/db.js
tests/lib/document.js
tests/test/branch-auth.js
tests/test/branch-noauth.js
tests/test/db-auth.js
tests/test/db-noauth.js
tests/test/document-auth.js

Return the response with verify functions to allow a more natural way of verifying the response.

tests: Use .then() with verify functions

---

src/core/document/query.pl

It turns out that we were not properly considering the specified type in the query interface, occasionally returning too many objects. Also, a subsumption check was wrong.

Query type fixes

---

src/core/api/api_document.pl
src/server/routes.pl
tests/lib/document.js
tests/lib/util.js
tests/test/document-get.js

* Add tests for the `prefixed` parameter for `graph_type=instance`
* Rename `Prefix` to `Compress` in `api_document.pl`
`prefixed` does not currently work with `graph_type=schema`. That issue is tracked in #801.

Add tests for `prefixed`

---

src/core/document/json.pl

type was introduced in frames but not yet used in the oneof unit test.

Fix oneof unit test

---

Makefile

This allows us to build the docs without worrying about the target path.

Fix target path for building docs

---

src/cli/main.pl
src/config/terminus_config.pl
src/core/api/api_init.pl
src/core/util/test_utils.pl
src/server/routes.pl

* test_utils: add option for env vars on spawn
Sometimes a test needs additional ENV vars even though it might not
be necessary to set them globally for every test. Therefore I
introduced the extra option called `env_vars`.
* Add authentication with insecure header for username
Some systems can be setup in such a way to offload user
authentication. For instance, you could set up TerminusDB in a
protected environment and use oauth2-proxy to secure it.
Therefore we now allow an insecure mode to be set in conjunction with
a custom user header to authenticate.
* Implement env vars with dynamic predicates and robust checking for
insecure header
* Check the env vars at initialization
* Closes #831

Add insecure user header for authentication

---

src/server/routes.pl
tests/test/document-auth.js

* Fixes #825
* Generalizes for `stream`, `string`, and `json_dict`

Force HTTP input encoding to UTF-8 for JSON

---

src/server/routes.pl

While working on #248, I found the part on writing the HTTP headers for the JSON stream rather confusing. Since I need to modify this, I refactored it to make it easier (for me) to understand.
* separated out the concerns of writing the headers and writing the stream/list separators
* used `true` and `false` instead of `var(...)` with a possibly unbound variable
* created the predicates `cors_json_stream_start` and `cors_json_stream_end` for clearly indicating when the JSON stream writing starts and ends
* removed unnecessary newlines (`~n`) for lists
* added comments

Improve writing HTTP header for JSON streams

---

src/core/api.pl
src/core/api/api_document.pl
src/server/routes.pl

For queries:
1. Create transaction
2. Generate IDs
3. Get document
This allows future work to extend the transaction creation without getting mingled in the generation of multiple document IDs.

Refactor document API: separate parts

---

src/bootstrap.pl

We use set_test_options which is a predicate defined in plunit. I do think we should avoid to rely on autoloading as much as possible.

bootstrap: import plunit as library

---

src/cli/main.pl
src/server/routes.pl

We don't want to rely too much on autoloading! 
```% rg print_prolog_backtrace
src/server/routes.pl
3510:            print_prolog_backtrace(current_output,Stack))
src/cli/main.pl
34:            print_prolog_backtrace(user_error, Stack)
```
But they don't import the prolog_stack module.

Explicit prolog_stack module import for printing backtrace

---

src/core/api/api_document.pl
src/core/api/api_error.pl
src/core/document.pl
src/core/document/json.pl
src/core/transaction.pl
src/core/transaction/database.pl
src/core/transaction/descriptor.pl
src/core/triple/triplestore.pl
src/core/util.pl
src/core/util/utils.pl

This pull request introduces id captures, a feature of the document interface where, when one does an insert or replace operation, they can capture ids, and refer to them elsewhere in the same insert/update stream.
This supports both backwards references (where you first capture an id, then refer to it later), and forward references (where you first refer to an id, then capture it later).

Id capture

---

src/core/document/json.pl
src/core/util/test_utils.pl

It was calling a predicate that no longer exists. Now it calls only predicates that do exist.

Fix print_all_documents test utility

---

Makefile

Some more Makefile changes
- I changed the doc build to use a relative path rather than an absolute path. As far as I can tell, using ./terminusdb works just as well as using the absolute path to terminusdb, and it saves us from having to do the magic to find the absolute path. This also means that make is once again able to detect that terminusdb has been built, which it couldn't do anymore due to mild path mangling in the absolute path target.
- I added all prolog, json, and ttl files in our source dir as a dependency to the terminusdb target. This means that running make will only rebuild terminusdb when one of these files has changed since the last build.

Fix makefile targets to support incremental build

---

README.md

Use scarf because it provides us with better metrics about the Docker image downloads.

README: use scarf

---

src/cli/main.pl
src/core/api.pl
src/core/api/api_document.pl
src/core/api/api_error.pl
src/core/api/api_woql.pl
src/core/document/json.pl
src/core/query.pl
src/core/query/path.pl
src/core/query/query_response.pl
src/core/query/woql_compile.pl
src/core/transaction.pl
src/core/transaction/database.pl
src/core/transaction/validate.pl
src/core/util.pl
src/core/util/data_version.pl
src/core/util/test_utils.pl
src/server/routes.pl
tests/lib/endpoint.js
tests/lib/index.js
tests/lib/params.js
tests/lib/woql.js
tests/test/data-version.js

* Read TerminusDB-Data-Version header
* Check it with the transaction data version and fail for mismatch
* Respond with possibly updated TerminusDB-Data-Version header
* Fixes #248

Add data versions for document and woql endpoints

---

.github/remove-old-docker-images.py

Deleting new dev tags is still possible, even if the cron only runs weekly. Therefore we now check the date of the image
and make sure that the image is older than 14 days AND contains the dev- prefix.

ci: only delete dev tags older than 2 weeks

---

src/core/util/data_version.pl
tests/lib/endpoint.js
tests/test/data-version.js

* Use the `commit_id` for a commit descriptor transaction.
* Fixes #922

Add data version support to commit resource

---

src/core/account/capabilities.pl
src/core/account/user_management.pl
src/core/api/db_fast_forward.pl
src/core/document/diff.pl
src/core/document/json.pl
src/core/document/patch.pl
src/core/document/query.pl
src/core/query/woql_compile.pl
src/core/triple/casting.pl
src/interactive.pl

My linter does not pick up `plunit` because it is not mentioned on the documentation here:
https://www.swi-prolog.org/pldoc/man?section=library
Therefore I had to import it manually. This pull request does the following:
- It imports plunit everywhere it needs to
- It forces autoloading to be disabled when you run `src/interactive.pl`. This increases the likelihood of missing library imports to be found since our developers use `src/interactive.pl` extensively. It's how I found out about the missing plunit imports as well.
It would be even better to disable autoloading entirely on the whole program. Unfortunately, this is not feasible right now as the SWI Prolog stable standard library contains an autoloading error itself, which Jan Wielemaker and I fixed here but which is not yet …

Force autoloading disabled on src/interactive.pl

---

src/interactive.pl

Revert because it slows down development for now

revert set_prolog_flag

---

src/core/api/api_document.pl

We jumped the gun on merging, and a unit test was actually broken. This is the fix.

fix unit test in captures

---

src/core/account/user_management.pl
src/core/api/api_db.pl
src/core/api/api_error.pl
src/core/api/db_create.pl
src/core/api/db_delete.pl
src/core/triple.pl
src/core/triple/database_utils.pl
tests/lib/organization.js
tests/test/organization.js

This pull will make it so that organization names are allowed to have a pipe in them. It also improves validation and error reporting on organization and database names.
This fixes #929.

Allow pipe in organization name

---

.github/workflows/ci.yml

This reverts commit 878744af3ee6c797b339ece2c88ca9f745c9b897.
It was a good attempt to speed up the Docker build, but it didn't always
work.

Revert "ci: cache Docker layers (#1002)"

---

src/config/terminus_config.pl

Two predicates were missing from terminus_config.pl, which were causing unit tests to fail locally (though not in the docker container and therefore not on CI).
These are now exported properly.

Add missing exports to fix unit tests

---

.github/workflows/ci.yml
.lint_config.pl

The linter now checks modules that are directly called.

Fix linter

---

src/server/routes.pl

For some values of the operation id, we were wrapping the id in quotes. This is unintended, as the exact given value should be reflected back into the json log. This should fix it.

Fix operation id logging so that nothing gets wrapped in quotes

---

.github/workflows/ci.yml

We need to make sure that we don't have regressions with the client's behavior. Therefore we need to run the client integration tests as well.

ci: try to run python tests

---

src/core/api/api_error.pl
src/core/document/json.pl
tests/lib/document.js
tests/lib/woql.js
tests/test/document-auth.js
tests/test/document-delete.js
tests/test/woql-auth.js

* Avoids a problem with the random key type where the submitted document does not contain an `@id`.
* Consolidate `document_does_not_exist` test into `document_not_found`
* Test for `document_not_found`
* Test for WOQL `UpdateDocument` with various configurations of IDs
* Refactor `json_idgen`: Lift out `key_descriptor`, pattern match on it in `json_idgen`

replace_document: check submitted ID against generated

---

src/core/document/schema.pl
tests/test/document-auth.js
tests/test/schema-check-failures.js

The schema check fails when attempting to insert this schema via the document interface:
```json
{
"@id": "unknown1"
"@type": "Class",
"field": "unknown2"
}
```
But the schema check does not fail with this schema:
```json
{
"@id": "unknown3"
"@type": "Class",
"field": { "@type": "Optional", "@class": "unknown4" }
}
```
I could not find a similar issue for this problem, so I created a test for it and submitted this PR as the issue. We should update this PR branch with the fix.

Refute schema for type family with unknown class

---

src/server/main.pl

For the sake of better logs, we should always print the version number at startup, so that when someone submits logs to us as part of their error report, we know what version that bug occurred on.

Added version number to startup banner

---

src/core/api/api_error.pl
tests/terminusdb.sh
tests/test/common-cli-errors.js

* Refactor `unknown_database` error to remove duplication
* Add `push` and `pull` to `error_type` for global errors

Globalize unknown_database, push/pull error types

---

.lint_config.pl
src/config/terminus_config.pl
src/core/transaction/descriptor.pl
src/core/transaction/validate.pl
src/core/triple.pl
src/core/triple/triplestore.pl

Most easy, always the same layer, users can't change it, can cache the initial result and never throw it away
This can change, so we have to check that what we're opening is still the most recent one.
This is the most difficult, because we need to think of policy around when layers should be evicted from memory.

Implement layer pinning

---

.github/workflows/ci.yml
tests/terminusdb.sh

* `ci.yml`:
- Use `$TERMINUSDB_DOCKER_IMAGE_TAG` for the Docker image tag name
* `tests/terminusdb.sh`:
- Use environment variables including `$TERMINUSDB_DOCKER_IMAGE_TAG`
- Better error reporting

$TERMINUSDB_DOCKER_IMAGE_TAG: ci.yml, terminusdb.sh

---

.github/workflows/benchmark.yml
.github/workflows/build.yml
.github/workflows/check.yml
.github/workflows/ci.yml
.github/workflows/docs.yml
Makefile

* Separate CI and PR workflows
- Use concurrency with commit SHA instead of `skip-duplicate-actions` to prevent redundant runs.
* Create reusable workflows for Build, Check, Benchmark.
- These are used by CI and PR.
* Create Docs workflow for ignoring docs changes but still running the required check of 'All checks passed'.
* Run unit tests with `swipl` instead of `terminusdb test`.
* Remove `deploy` since it doesn't work.

Improve GitHub actions

---

src/server/routes.pl
tests/test/compression.js

This allows the server to to handle requests with the gzip and deflate content encodings for some endpoints. I would consider this preliminary support. It has not been thoroughly tested. Consequently, the accepted encodings are not broadcasted in the response header.

Add initial support for Content-Encoding with gzip and deflate

---

.github/workflows/ci.yml

It should succeed only if we do not need to push the Docker image.

Fix all_checks_pass_without_build

---

.github/workflows/non-docker.yml

Run `make test` instead of `./terminusdb test`, since the latter does not run all of the unit tests.

ci: non-docker: make test

---

src/server/routes.pl

This adds `chunked` to the configuration of the document handler. Doing this should allow streaming output, though unfortunately I don't have a local test set large enough to actually test this properly.

set the document handler to chunked to support streaming output

---

src/server/routes.pl

The document endpoint can take its sweet time to actually retrieve all documents if you're exporting a huge database. Since that use case is fine on localhost and not indicative of an error, I've disabled the timeout for this particular endpoint, much like how it is also disabled for various other endpoints.

Disable timeout on the document endpoint

---

src/core/api/db_push.pl
src/core/transaction.pl
src/core/transaction/ref_entity.pl

The InitialCommit is a special type of commit that just contains prefix information. It gets overwritten by a ValidCommit on first commit. However, the current push logic sees this initialcommit and thinks it is a potential conflict.
This pull request will consider the InitialCommit to be equivalent to there not being a commit at all, and happily overwites it.

Allow a push to overwrite a branch containing just an initial commit

---

Dockerfile

We were apparently on a version of tus that was more than a year old, causing a discrepancy between the library version we were using locally on dev machines and the one that ships with the container.

Upgrade tus library to latest version in the docker

---

src/core/api/db_create.pl

`create_db_unfinalized` called in `create_db`, but it is also exported
and can be called instead of `create_db`, so we should be checking
argument error conditions there instead of `create_db`.

Validate in create_db_unfinalized, not create_db

---

src/config/terminus_config.pl
src/core/api/api_init.pl
src/core/util.pl
src/core/util/file_utils.pl
src/core/util/utils.pl

* Change `getenv_default` to use the default when the env var is empty
This came up when using `TERMINUSDB_SERVER_DB_PATH=`, which resulted
in `getenv('TERMINUSDB_SERVER_DB_PATH', '')`, which resulted in
`db_path('/')`.
* Add tests for `TERMINUSDB_SERVER_DB_PATH`
* Use `absolute_file_name` to determine absolute path
* Remove unused path predicates (`registry_path`, `tmp_path`)

Handle empty env var values

---

.github/workflows/remove-old-docker.yml

They don't have access to the secrets which always make the CI cron fail.

ci: don't delete old docker images on fork

---

src/core/query/woql_compile.pl

Being relatively new to WOQL, I encountered a problem where I used `v(X)` instead of `v('X')` as a variable name. The experience looked like this:
```
$ ./terminusdb query admin/issue188 "v(X)=a"
[29] dict_create(_10512,_10514,[... = a])
[26] findall_loop(_10558,query_response:(...,...),_10562,[]) at /Users/leather/.local/lib/swipl/boot/bags.pl:99
[25] setup_call_catcher_cleanup('$bags':'$new_findall_bag','$bags':findall_loop(_10628,...,_10632,[]),_10610,'$bags':'$destroy_findall_bag') at /Users/leather/.local/lib/swipl/boot/init.pl:661
[21] '<meta-call>'('<garbage_collected>') <foreign>
[20] call('<garbage_collected>') at /Users/leather/.local/lib/swipl/boot/init.pl:499
[19] catch(database:call(...),fail_transaction,database:(_10758=true)) at …
```

Catch bad variable names in WOQL

---

.github/workflows/check.yml
.github/workflows/ci.yml

This allows us to use `check.yml` outside of the repository and
guarantee that every use of `actions/checkout` gets the same ref. It has
happened that the `HEAD` of the default branch changes in the middle of
these multiple checkouts. With this change, that won't happen.

Accept test_ref in check.yml

---

.github/workflows/ci.yml

`github.ref` may point to `refs/head/main`, and the SHA to which it
points can change during the run.
`github.sha` points to `b389a2830b119c8b6c4b71a6984b733837231d3a`, which
never changes during a run.

Use github.sha, not github.ref

---

src/cli/main.pl
tests/test/cli-doc.js

The use of `(s)` in `Document(s)` has been irritating me.

CLI doc insert: use singular and plural messages

---

.github/workflows/ci.yml
docs/release-steps.md
src/config/terminus_config.pl

* Remove use of release branch (currently `v10.0`) and use only tags
* Automate updating of versions by setting them in
`.github/workflows/ci.yml`:
- `LAST_RELEASED_VERSION`
- `CURRENT_REPO_VERSION`
* Generate parts of files with the versions above:
- `docs/release-steps.md`
- `src/config/terminus_config.pl`

Simplify release process

---

src/config/terminus_config.pl

Adding worker count default as number of CPUs

---

.dockerignore
.github/workflows/check.yml
.gitignore
Dockerfile
Makefile
distribution/Makefile.deps
distribution/Makefile.prolog
distribution/Makefile.rust
docs/BUILD.md
src/bootstrap.pl

* Split the `Makefile` into parts that can by copied by the `Dockerfile` for
different stages of the build.
* Use `Makefile`s for key parts of the build in the `Dockerfile` to reduce
duplication of the build process.
* Improve build caching in the `Dockerfile` by putting `apt-get` before `COPY`.
- This has the effect of speeding up the Docker build significantly. Cached
builds now take on the order of 10-15 seconds.
* Change these to allow the `Dockerfile` to support building both the community
and enterprise distributions:
- `make enterprise` ->
`make DIST=enterprise`
- `docker build . --build-arg MAKE_ARGS=enterprise` ->
`docker build . --build-arg DIST=enterprise`
* `make install-deps` now always updates and rebuilds the packs.
- `swipl` doesn't update if the pack directory is there.
* …

Improve Makefile and Dockerfile

---

src/rust/Cargo.lock
src/rust/terminusdb-store-prolog/Cargo.toml

This pulls in the latest version for terminusdb-store, resolving the double tokio import.
Fixes #1225.

Raise store dependency to 0.19.9 and update dependencies

---

README.md

I noticed an error in the example:
First it adds a schema to `admin/example1` but then it inserts it in `admin/example`. This is not where the schema was created, so I changed both these examples to `admin/example`. I also added the db create command just in case people forget to create the database first.

README: fix CLI example

---

.github/workflows/ci.yml
distribution/snap/snapcraft.yaml
docs/release-steps.md

The Snap will now be published on every release we do instead of manually.
This should make sure that every snap is released when we tag a new version. We use cog templating to change the version
number each time.
The CI works the following way:
1. We have a workflow file that builds a snap, it runs automatically each night. But is also callable from other GitHub workflows.
2. When we tag push, we call and trigger this workflow, download its artifact and publish it on snap.
Possible improvements for later:
- Instead of using cog, we can programmatically determine the version, see: https://snapcraft.io/docs/using-external-metadata#meta-scriptlet
- We could publish the nightly snap as an `edge` release instead of a stable one. This would be cool for users that to try a recent experimental …

Add proper CI support for Snap

---

.github/workflows/check.yml
src/config/terminus_config.pl
src/server/routes.pl

Introduce a new ENV variable called TERMINUSDB_JWT_SUBJ_CLAIM_NAME. By default it is set to the `http://terminusdb.com/schema/system#agent_name` but it can be configured by the user to mean something else as well.
This should solve: https://github.com/terminusdb/terminusdb/issues/1237

Add configurable claim name for JWT tokens

---

docs/terminusdb.1.ronn
src/cli/main.pl
src/core/api/api_patch.pl
tests/test/capabilities.js
tests/test/cli-diff.js

There was a small bug where a full removal of a document didn't properly bind the ID for that deletion.
Also, it should now be possible to directly specify a branch to diff, instead of a commit id.

Allow branches to be diffed directly, and small bugfix in uniqueness

---

.github/workflows/check.yml
tests/package.json

Lint JS first and not after the tests. This saves a lot of time, since sometimes you are waiting for tests to pass and then suddenly see the linting fail.

Fix JS lint order

---

docs/openapi.yaml

The trailing slash is not how the api should be called.

openapi: remove trailing slash in db endpoint

---

src/core/document/validation.pl

Insufficiently strict about blast radius! This includes queries which change *nothing* which is a disaster since the prior layer is then rechecked on every search.

Fix validation

---

src/core/triple/literals.pl
tests/lib/api/response.js
tests/lib/triples.js
tests/test/triples.js

Fixes the triples marshalling. Previously, string literals we marshalled as "string"@en instead of "string"^^xsd:string.

Marshall lits

---

src/server/routes.pl
tests/test/triples.js

If the accept header has "text/turtle" it will now return a turtle string instead of a turtle string as JSON.

Allow turtle to be returned from triples endpoint

---

src/core/query/jsonld.pl

As discussed in #1418 there is a bug in prefix matching where trying to insert an id like `@base:Foo/a:b` doesn't work. Our prefix expander expects only a single colon to appear in the id. However, it is actually allowed to have colons in the actual URI as well.
This change changes the prefix matching so that everything up to the first colon is considered the prefix, and everything after (including subsequent colon characters) is considered the suffix.

match prefixes that further colons are part of the suffix

---

src/core/api/api_error.pl
src/core/api/api_log.pl
tests/test/log.js

This ensures that we only attempt to build a log from things that actually have logs (branch and commit descriptors).

Error when retrieving log on something with no history

---

src/core/api/api_document.pl
src/core/document/json.pl
tests/test/document-full-replace.js

When doing a full replace on instance data, the insert logic was not properly suspending inserts until all captures were known, causing the code to attempt to insert unbound triple data. This led to an ugly stack trace.
Fixes #1398.

Fix captures in full replace

---

src/core/api/api_document.pl

Keep backtraces when catching errors in document mutation. We're currently dropping them, making debugging tricky.

Catch document mutation errors with backtrace

---

src/rust/terminusdb-community/src/lib.rs
src/rust/terminusdb-community/src/log.rs

This introduces some macros for formatted logging from rust using the json_log facility from prolog.
In the future I'd like to add logging of actual json objects, but we'll need a good conversion from rust json objects to prolog dicts for that and that's a bit of a bigger slice of work than simply going with formatted strings for now.

allow use of the prolog logger from rust

---

distribution/Makefile.deps

Update dashboard to the new version.
Some changes include that the dependencies are updated and that it has proper titles now (it should display TerminusDB Dashboard instead of TerminusX for the local build)

Update dashboard version to 0.0.7

---

Dockerfile

Upgrade SWI Prolog version to v8.4.3 (current stable) from v8.4.2. Lets make sure that all the tests pass and that the password_hash is still backwards compatible.

Upgrade SWIPL version

---

Dockerfile

Even though the segfault does not seem to happen on the Debian stable versions, I still feel very uncomfortable with this not patched in.

Dockerfile: use patched version of swipl

---

src/core/document/inference.pl
src/core/document/json.pl

One case was not covered in value checking in the inference.  `sys:Unit` optionals (which are silly because they are isomorphic with bool) are now possible.

Fixing sys unit with Option

---

.github/workflows/arm.yml

An hour for building a Docker image is just sad. On a real arm64 server it only takes 11m.
Example: https://github.com/terminusdb/terminusdb/actions/runs/3444496724

Try docker build on custom runner from buildjet

---

src/load_paths.pl

This makes it possible to choose another dashboard path at compile time.
The ENV variable is called TERMINUSDB_DASHBOARD_PATH. If the ENV variable is not set, it will use the `dashboard` directory relative to the build directory.

load_paths: add ENV variable for dashboard path

---

src/rust/terminusdb-community/src/schema.rs

we accidentally walked the inheritance graph in the wrong direction.

Fix set property inheritance in doc retrieval

---

src/rust/terminusdb-community/src/graphql/mod.rs
src/server/routes.pl

The graphiql endpoint always assumed `terminusdb` to be accessible on localhost. Mostly because the `graphiql` endpoint is intended as a tool for developers. However, there are certainly cases where you would like to access it under different domains.
Therefore I removed the host and port from the path as it now assumes that if you visit for instance:
`http://some-site.xyz:9090/graphiql/admin/test` that your terminusdb server is also on `http://some-site.xyz:9090`

Graphiql no fixed host

---

src/cli/main.pl
src/interactive.pl
src/start.pl

It does not serve a purpose since it does not actually work. And even when I got it to work by loading the http_log module it would only log the HTTP requests and not do any other sort of logging by TerminusDB.
Fixes #1572

Remove TERMINUSDB_LOG_PATH ENV variable

---

tests/package-lock.json

eslint-mocha had to be upgraded in order to fix a deprecation warning.

package-lock: fix deprecation warning by updating

---

src/server/main.pl

If the LOG_FORMAT ENV variable is set to json, it will print a JSON welcome message instead of the normal text welcome message.
This is better because it is awkward if the logs are streamed to a JSON parser but it does not always contain valid JSON.
The welcome message in this particular commit looks like this:
```
{
"message": "Welcome to TerminusDB ! You can view your server in a browser at http://localhost:6363",
"version": "10.1.11",
"args": "[serve,help(false),interactive(false),memory(_250)]"
}
```

server: add JSON formatted welcome message

---

.github/workflows/arm.yml
.github/workflows/build.yml
.github/workflows/check.yml

Use custom runners for our CI. Unfortunately, since we don't execute test files in parallel, it is not a big improvement but still cuts of a few minutes. In the future, we should aim to reduce shared state in tests in order to get them run in parallel.

Use custom runners for CI

---

src/core/api/api_error.pl

It would print a dirty stack trace otherwise instead.

api_error: add missing fetch requires repo error

---

src/rust/terminusdb-community/src/doc.rs
src/rust/terminusdb-community/src/value.rs

The document interface was retrieving array indexes as u32, but they are actually stored as NonNegativeIntegers (despite actually being usize). This fixes the retrieval so arrays work properly in the doc interface.

retrieve array indexes using the correct type

---

src/rust/terminusdb-community/src/graphql/schema.rs
tests/test/graphql.js

Enums were being retrieved as values in optional fields for graphql, but they're actually nodes. This fixes that.

Support enums in optionals for graphql queries

---

src/rust/Cargo.lock
src/rust/terminusdb-community/Cargo.toml

It turns out that the version of smartstring that juniper is using has some weird issues which caused certain strings to get mangled unpredictably. In order to quickly resolve this, we've set up a temporary juniper fork where we've upgraded the smartstring dependency to version 1.0, which doesn't appear to have the same issue.
This is obviously a temporary fix to resolve a blocker for us. We should coordinate with the juniper maintainers to hopefully get a proper fix of juniper out, or alternatively wait for their release of 0.16 (which seems to involve a lot of changes to their codegen, so unfortunate;y that won't be an easy upgrade).

Use patched juniper with updated smartstring dependency

---

Dockerfile

This reverts commit 2c48ad4233e47fa60083487dddbbd175320a447b.
We should be fine with using Debian stable as the problem we tried to solve was caused by something else.

Revert "Dockerfile: use Ubuntu instead of Debian (#1683)"

---

src/core/api/db_fetch.pl
src/core/api/db_push.pl

We should be doing a version check when sending/receiving pack files between servers. First step for doing so is actually submitting a version on requests to the pack and unpack endpoints.

Submit terminusdb version header to pack/unpack

---

src/core/triple/triplestore.pl
tests/test/data-version.js

The label for the system schema graph is checked every time the system descriptor is opened, even though the system schema graph should not be changing. While it's technically possible for the system schema graph to change, this is probably rare enough that we should just be pinning it anyway.
This PR pins the label so that we save on these label lookups. This is especially useful for environments with slow label lookups.
In the future we should probably fully disable writes to this graph.

pin the system schema graph to prevent superfluous label lookups

---

src/config/terminus_config.pl
src/core/account.pl
src/core/account/user_management.pl
src/core/api/api_access_control.pl
src/core/api/api_init.pl

It turns out that password hashing is taking up a significant amount of time in TerminusDB due to the hash function being set to cycle 2^17 times, leading to hash costs in excess of 100ms. This is completely unacceptable for an API.
This PR limits the cost to 10, which means 1024 cycles. IMO there's little need for any cycling so I'm open to lowering this even more. At this point though it looks like costs for single requests fall into the noise.

limit the default password hash cost to 10 for less roundtrips

---

Dockerfile
src/config/terminus_config.pl
src/core/triple/triplestore.pl
src/library/terminus_store.pl
src/rust/Cargo.lock
src/rust/terminusdb-store-prolog/Cargo.toml
src/rust/terminusdb-store-prolog/src/lib.rs
src/rust/terminusdb-store-prolog/src/store.rs

For cloud deploys it can be useful to separate the logic of how labels are looked up from the server, so that some external component can do something cool and custom.
This PR uses the [terminusdb-grpc-labelstore](https://github.com/terminusdb-labs/terminusdb-grpc-labelstore) project to offer the option to configure a grpc endpoint for a label server to use instead of looking things up on the filesystem.

gRPC label store

---

src/server/routes.pl

This PR adds the "skip authentication" option to the `ok_handler` because the ok endpoint doesn't need authentication.

Ok handler no auth

---

.github/workflows/ci.yml

It is pretty unstable. We should mature it a bit and then enable it again. But now, it fails too many times in order to make it run reliably.

Remove benchmark in CI

---

src/core/api/db_clone.pl

The database was being left in an inconsistent state, requiring a force delete. Since we're in a code path where we just created the database, we know it is safe to delete it. This is the more user friendly approach.

When a clone fails, delete the database

---

.github/workflows/ci.yml
distribution/Dockerfile.utility

This is useful for debugging purposes. Currently it waits until a tag of TerminusDB is pushed, then it replaces the Dockerfile.utility with the right tag and builds and pushes that one as well with the same tag but with a different image name.

Utility image

---

.github/workflows/ci.yml
distribution/Dockerfile.utility

This reverts commit ef0d849ca3601460e83aa938504374507ad3db1f because of the failing CI. I know what is wrong but it is better to get CI up and running quickly before taking more time to fix the issue.

Revert "Utility image (#1714)"

---

src/core/document/json.pl

This PR introduces support for insertion of nested documents with key dependencies.
This was previously not working because we wouldn't know the id in time to do this, as id generation of parents strictly happened before id generation of children.
This PR reorders the id generation, so that key fields have their id generated first.

Support insertion of nested top-level documents with key dependencies

---

src/core/query/json_woql.pl
src/core/triple/casting.pl

This fixes a very serious bug in the interpretation of gYear from integer objects. Previously it would always crash with a type_error.

Gyear behaviour patch

---

src/core/account/capabilities.pl

Getting the list of DB's for a particular user was very slow because an inefficient query. This query is now reordered to make it faster. Measurements show that the performance increased about ~9 times.

Fix slow db query that improves /api/db speed

---

Dockerfile

This makes it easier to read stack traces and the like.

Add binutils for easier debugging (addr2line)

---

src/server/routes.pl
tests/lib/api/response.js

Fixes #1728 .
In addition to returning the correct status code for deletes, this will also only use `Transfer-Encoding: chunked` for the get version of the document api endpoint. We were running into an issue where with this header present, the swipl http logic would insert chunk information even after an empty response. This is probably a swipl bug.
We'll need to verify that this doesn't break the javascript or python client.

Return 204 on doc delete (and disable chunking for non-gets)

---

docs/openapi.yaml

This improves on the openapi specification for the squash and reset endpoints, and adds documentation for rebase.
Fixes #1628

openapi doc improvements for squash, rebase, and reset

---

src/core/triple/check_db.pl

Every call to `api/info` would be opening a store version file to check the store version.
I think we can assume that this version won't be updating while the server is running. Since we're calling this endpoint on each client initialization it's probably good to cache the result instead.

table the check_db predicate to prevent superfluous disk accesses

---

src/cli/main.pl
src/core/api.pl
src/core/api/api_log.pl
src/core/document/migration.pl
src/core/triple/database_utils.pl
src/core/triple/literals.pl
src/server/routes.pl

This PR adds a verbose mode to logging such that you can see migrations, and improves when migrations can be inferred to some conditions in which it was rejected previously.

Migration improvements

---

src/core/document/json.pl
src/core/document/schema.pl

Cascading delete on choice properties in the schema was not properly working as choice was not deemed a type which needed to be transitively explored.

Nukes choice objects properly

---

src/server/routes.pl

This fixes a memory leak where simple document gets would not get the private tables in SWI Prolog wiped.

Fix memory leak by abolishing tables on each request

---

src/rust/terminusdb-community/src/doc.rs

We were seeing that while parallel fetching documents, generating their json struct can easily outperform printing the json. This causes documents to get queued up in a message channel, increasing the memory footprint without improving performance.
This PR switches to a synchronized channel, blocking sends when there's more than a certain amount of documents still in the message queue.

Block sends of documents to print beyond a multiple of thread count

---

.github/workflows/ci.yml

If a new release is tagged, we also push a major tag now without containing the full version. For instance, when someone pushes a new tag called v11.0.4, it will update the v11 tag with this new image.
The reason for this is that it is easier for users to track minor releases this way.

ci: add major tag

---

docs/openapi.yaml

Otherwise it gets parsed by yaml loaders as a datetime

openapi: use string for date

---

.github/workflows/check.yml
.github/workflows/ci.yml

It uses a newer version of Node which prevents all the deprecation warnings

Upgrade actions download/upload artifact

---

src/config/terminus_config.pl
src/core/api.pl
src/core/api/db_fetch.pl
src/core/api/db_pack.pl
src/server/routes.pl

Instead of waiting for the pack to be finished, we now poll the remote server for when the pack is finished and then fetch the pack.
We use a 5 second interval between the polls, which is long but might be better to save resources.

Fix clone timeouts by polling remote server

---

src/core/api/api_indexer.pl

The predicate `is_super_user` was used but the appropriate module wasn't imported.

Fix missing import for superuser check

---

src/rust/terminusdb-community/src/graphql/frame.rs

We were not properly calculating subsumptions in graphql. Whenever there was a multi-level hierarchy, any intermediates would not be including themselves in the subsumption.
This pull fixes that.
Fixes #1792 .

Fix multi-level subsumptions in graphql

---

docker-compose.yml

The endpoint should be suffixed by /api/index and the default buffer amount was way too big

Reduce buffer_amount default and fix endpoint

---

src/config/terminus_config.pl
src/core/document.pl
src/core/document/migration.pl
src/core/document/validation.pl

Improves the performance of instance checking by not doing it at all if an inferred migration exists. The reasoning is that the schema migrations fix the instance data appropriately as is, and so any inferred migration is sufficient to avoid a global schema-instance check which is very expensive with large datasets.

Performance bump with inferred migrations as schema-instance check

---

docker-compose.yml

The OPENAI_KEY was set in the wrong container and VectorLink has been updated to log more useful things

docker-compose fixes

---

src/rust/terminusdb-community/src/graphql/filter.rs
src/rust/terminusdb-community/src/graphql/query.rs
src/rust/terminusdb-community/src/path/compile.rs
src/rust/terminusdb-community/src/path/parse.rs

This PR introduces a way to match on a node id through the filter object.
So far it's only been possible to match on id directly as part of the graphql operator looking up an object from a collection. It was not possible to match on the id of one of its children.
This introduces the syntax for it, and internally makes use of path queries to come up with a candidate iterator that should be more efficient than going through all types and checking.

Graphql id deep match

---

src/core/api/api_graphql.pl
src/rust/Cargo.lock
src/rust/terminusdb-community/Cargo.toml
src/rust/terminusdb-community/src/graphql/mod.rs
src/rust/terminusdb-community/src/graphql/schema.rs

Adding an LRU cache to graphql to keep the most recent 10 terminusdb schema compiles in memory, speeding up repeated graphql queries, especially when the schema is pretty big.

simple lru caching for graphql context

---

src/rust/Cargo.lock
src/rust/terminusdb-community/Cargo.toml
src/rust/terminusdb-community/src/graphql/schema.rs

We were special-casing 'id' in our graphql schema generation, as a  relic from an earlier time when this clashed with our own internal ids. Since we moved those to '_id', there's no sense in special-casing id anymore.

Ensure that id fields work in graphql

---

src/rust/Cargo.lock
src/rust/Cargo.toml
src/rust/terminusdb-community/Cargo.toml
src/rust/terminusdb-store-prolog/Cargo.toml

use newer swipl version, mostly for better macro expansions.

raise swipl versions

---

distribution/docker-compose/bootstrap_storage.yaml
docker-compose.yml

We don't need to repeat all the environment variables anymore but they can all be declared globally in the .env file
I also added a new bootstrap_storage override yaml which can be run using:
`docker compose -f docker-compose.yml -f distribution/docker-compose/bootstrap_storage.yaml`

Simplify docker-compose

---

src/core/document/json.pl
src/core/document/schema.pl
src/rust/terminusdb-community/src/doc.rs

This changes the document extraction logic so that unfold cycles are expected and handled by emitting an IRI instead of an unfolded document.

untrusting cycle detection during document extraction

---

docs/openapi.yaml
docs/terminusdb.1.ronn
src/cli/main.pl
src/core/api.pl
src/core/api/api_woql.pl
src/core/document/json.pl
src/core/query.pl
src/core/query/ask.pl
src/core/query/query_response.pl
src/core/query/reorder.pl
src/core/query/woql_compile.pl
src/server/routes.pl

This PR fixes the ordering of nots such that they are delayed effectively until bindings can be obtained. It also moves get document late in the query order as it is a relatively expensive search operation even when its id argument is bound.
This PR does not yet move query order optimisation into a feature which can be turned on / off, which is why it is in draft.

Fix reorder of not and get document

---

src/config/terminus_config.pl
src/rust/Cargo.toml
src/rust/terminusdb-community/src/doc.rs
src/rust/terminusdb-community/src/graphql/schema.rs

While infinite recursion is prevented in document retrieval, a schema can still be constructed in such a way that retrieving a document essentially pulls in the entire database. This is further worsened by certain crosslink situations which cause parts of the database to be retrieved many times, resulting in huge documents that blow up terminusdb.
This PR sets up a global limit for how much work is allowed to be performed per document retrieval.

ensure document retrieval doesn't use up a great amount of resources

---

docker-compose.yml

the docker-compose was serving up two ports, with dashboard using one to retrieve its static files and the other to do actual api calls. This changes the situation so that everything uses a single port, namely the CR API, which now also properly proxies API calls to terminusdb for anything it doesn't recognize.

Alter docker-compose to let the cr api act as proxy middleware

---

src/core/query/definition.pl
src/core/query/reorder.pl

An incorrect assumption about modality calculations can cause reordering failures due to the fact that skeletons exist in WOQL (dicts and lists can have deep structure). We do not have a modality concept employing skeletons so we employ a more conservative approach which calculates a non-ground structure as ?. We can explore employing a better skeleton mode later (for instance count([X,Y,Z],Count) does not need its variables bound as it is parametrically polymorphic in the values of the list).

Fix mode calculation on skeletons

---

src/core/query/definition.pl

Bug in calculation of costs for `or` mixed with `limit`. This fix should generically deal with cost overflows.

Float cost overflow

---

src/rust/terminusdb-community/src/path/parse.rs

Allows the use of whitespace surrounding predicates in path queries for graphql

Add whitespace to patterns

---

src/core/query/definition.pl
src/core/query/reorder.pl
tests/test/woql-auth.js

This adds propagation of metavariables during cost calculation to ensure we get meaningful costs, and also relaxes the mode of the equality/unification operator to ? ?.

Reorder with metavariable propagation and relax unification mode.

---

docker-compose.yml

For some reason, the default docker-compose.yml we recommend came with insecure user forward headers configured. This does not appear to be necessary for a working local dashboard, but does introduce a security risk if people try to use the default docker-compose in a production environment.
Although the comments in docker-compose.yml do point this out, and warn users to remove these headers in production scenarios, people unfortunately don't always read carefully before deploying things. It is better to default to a safer configuration.
This PR removes the headers from docker-compose.yml.

Remove default insecure headers from docker-compose config

---

docker-compose.yml

Reverts terminusdb/terminusdb#2039
vectorlink currently relies on this config. Changing this back for now, but will restore when vectorlink is fixed.

Revert "Remove default insecure headers from docker-compose config"

---

README.md

doc: style: display @metadata and @unfoldable keywords as code, not plain text

doc: style: display @metadata and @unfoldable keywords as code

---

.github/workflows/arm.yml
.github/workflows/ci.yml
src/rust/Cargo.lock

This removes superfluous qemu initialization from arm builds (which run on arm machines and so do not need qemu).

changes to arm build process

---

README.md

It was confusing to me, that README mentioned OPENAI_KEY like it was mandatory, til I found the clarification in documentation portal. This should help others not to get scared at first glance of this repo

README copy of clarification note about OPENAI_KEY not being mandatory

---

distribution/Makefile.deps
docs/RELEASE_NOTES.md

Notes:
* TerminusDB tested with push and pull between TerminusDB instances
* Makefile.deps updated with reference to tus 0.0.16 tag (with content-length fix)
* Release notes updated with 11.1.13 version
* TerminusDB was built successfully using command `docker build --no-cache -t terminusdb-content-length`

Issue/2135 double content length, fixes #2135

---

docker-compose.yml

As described in https://github.com/terminusdb/terminusdb/issues/1939#issuecomment-1675959894 change-request-api uses the environment-variable "USER_KEY" instead of "TERMINUSDB_ADMIN_PASS". The changes should help new users with the correct configuration.

Correction of the environment-variable in docker-compose.yml

---

.github/workflows/arm.yml
.github/workflows/build.yml
.github/workflows/snap.yml

Let's restart the self-hosted runner again.
Looks like it was only changed in the build script.

Fix issue with finicky tests needed performance runners

---

README.md

The terminusdb.com homepage is down at the moment. This redirects the link on the repo landing page to the .org site.

Update README.md, fixes #2163

---

src/core/query/json_woql.pl

The RemovedTriple and RemovedQuad AST keywords are inconsistent with the original woql spec, and the clients seem to prefer the DeletedTriple and DeletedQuad syntax. The DeletedTriple syntax is used inconsistently in other parts of terminusdb. Settling on the original woql.json naming.
Some changes to the clients will be done as well to conform

Ensure consistent AST with DeletedTriple and DeletedQuad (#1617)

---

.github/install-swi-prolog.sh

There is a new homebrew path for swipl that make the macos build fail. This sets the correct path for the swi-prolog installation.

Update to new homebrew path for swipl

---

.github/workflows/arm.yml

https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts
and the linked page:
https://docs.docker.com/build/cache/backends/gha/
Unsure if it targets it exactly, but seems to be related that the version is too low (v3 vs v6)

It seems the docker/build-push-action also needs to be updated

---

.env-template
docker-compose.yml

This makes the docker-compose.yml file easy to use again and fixes the discrepancies between the two parts.

Improve the docker-compose file to make the project start (Fixes #1939 and fixes #2051)

---

.github/workflows/ci.yml
.github/workflows/code-lint.yml
.github/workflows/docker-amd64-build.yml
.github/workflows/docker-arm64-build.yml
.github/workflows/docker-image-test.yml
.github/workflows/generate-docs.yml
.github/workflows/native-build.yml
.github/workflows/publish.yml
.github/workflows/remove-old-docker.yml
.github/workflows/snap.yml
README.md

This PR extracts Docker image builds into separate actions (on demand, can be scheduled). It hooks documentation generation to the push event and separates the publish action (on demand, could be hooked up to the release event).
Remaining tasks: fix snap and version change. (The next PR will make ci.yml obsolete.)

Reorg docker build actions (1/2)
